### ISSUE TITLE
Action proposal: Control AirPods Noise Cancelling

### ISSUE THREAD

**Issue by FlorianWendelborn** [sindresorhus/Actions#10]
### Description

I don’t know if third-party apps are able to do this, but if possible this would allow users to enable/disable noise cancellation for example depending on location, or the open app.

**Comment by sindresorhus** [comment]
This is unfortunately not possible. Apple does not expose such capability to third-party apps. I would recommend submitting feedback to Apple about adding Shortcut actions to control AirPods.
