### ISSUE TITLE
Bug: „is silent mode on?“ only reliable after second call

### ISSUE THREAD

**Issue by schlagmichdoch** [sindresorhus/Actions#101]
Wenn the action „is silent mode on?“ is called the first time after switching silent mode on/off it returns the old state. It returns the correct value only after calling it a second time.

As a workaround I put the action in a loop which executes it 2 times.

---
Actions 2.2.0 (35) - com.sindresorhus.Actions
iOS 16.2
iPhone10,4

**Comment by sindresorhus** [comment]
Can you try the latest update (2.2.1) and let me know if it works there? You may have to restart your device after updating.

**Comment by schlagmichdoch** [comment]
I could not reproduce the issue anymore. Thanks for fixing!

**Comment by sindresorhus** [comment]
Thanks for confirming 👍
