### ISSUE TITLE
Action proposal: Accept audio file from Memo app

### ISSUE THREAD

**Issue by mittalyashu** [sindresorhus/Actions#107]
### Description

| Preview |
| --- |
| <img width="643" alt="CleanShot 2023-01-30 at 12 32 46@2x" src="https://user-images.githubusercontent.com/29014463/215409576-74bad840-78b6-4f3f-96b4-6fcf8f968c9c.png"> |

**Comment by sindresorhus** [comment]
There's no way to do that. Voice Memos does not have any action that returns the recording. You will have to send a feature request to Apple.
