### ISSUE TITLE
Action proposal: is CarPlay Connected

### ISSUE THREAD

**Issue by nicohery** [sindresorhus/Actions#109]
### Description

Would it be possible for the get an action on connecting iPhone to CarPlay ?

**Comment by sindresorhus** [comment]
This is unfortunately not possible. Anything that interacts with CarPlay has to apply for a special entitlement with Apple.

Maybe this can help: https://www.reddit.com/r/shortcuts/comments/e4zxrh/can_a_shortcut_check_if_carplay_is_connected_in/
