### ISSUE TITLE
Action proposal: Rounding to nearest interval

### ISSUE THREAD

**Issue by hexagonsun24** [sindresorhus/Actions#11]
### Description

Siri Shortcuts has a rounding function to round up or down to the nearest X place digit. However, there are some scenarios were being able to round to the near x Interval would be helpful. For example, having a function to round to the nearest multiple of 5, 15, or 25 (or any other number for that matter). This would mirror the [Excel function MROUND](https://support.microsoft.com/en-us/office/mround-function-c299c3b0-15a5-426d-aa4b-d2d5b3baf427). I believe it's a relatively simple modulo function, which can be replicated with a number of steps already in Shortcut, but having a single step to do this would be fantastic.

**Comment by sindresorhus** [comment]
Good idea. I'll add this soon.
