### ISSUE TITLE
Action proposal: play haptic feedback

### ISSUE THREAD

**Issue by TheThonos** [sindresorhus/Actions#113]
### Description

Gives quick haptic feedback, like when you tap and hold on an app

**Comment by sindresorhus** [comment]
Already exists as `Generate Haptic Feedback`.

**Comment by madysondesigns** [comment]
This action is so awesome! One question – when I use it, it briefly kicks me to the Actions app before continuing with the shortcut. Is this expected behaviour or am I doing something wrong?

**Comment by sindresorhus** [comment]
The action has to momentarily open the main app as haptic feedback can only be generated from the app.

**Comment by madysondesigns** [comment]
Got it, and I assume that's a limitation on Apple's end. I also just noticed this is clearly mentioned in the action info so that's on me for not RTFM 🙂 Thanks!
