### ISSUE TITLE
Getting global var on Apple Watch triggers an extra step that require manual selection of the variable

### ISSUE THREAD

**Issue by caenrigen** [sindresorhus/Actions#116]
### Description

Hi there, thank you for the great work!

I run into an issue with the recent Global Variables (great feature by the way!).

When I run a shortcut that makes use of `Get global text variable` (or get any global variable) it works great on macOS and iPhone but when I run it from the Apple Watch it asks me to choose the Global variable manually.

Is this intended behaviour or a bug? Is it some kind of limitation of the WatchOS has?

It is inconvenient because I was using the Global var as way to pass information between shortcuts in a more easy way than created some nested Dictionaries, etc..

Hope this helps to improve the Actions app, cheers!

### macOS/iOS version

macOS Ventura 13.2 / iOS 16.3.1 / watchOS 9.3.1

### Shortcut URL

https://www.icloud.com/shortcuts/f1e22aabf465444b806cb1d59b9a2cd1

**Comment by sindresorhus** [comment]
The Actions app does not run natively on watchOS, so in this case, I assume Shortcuts is running the shortcut remotely on your iPhone. So any problems with that is a problem with Shortcuts.

**Comment by caenrigen** [comment]
Thank you for the reply!

> Can you try writing the variable name in a Text action and then passing that as the key?

Not sure what you mean, but I was already doing this

> The Actions app does not run natively on watchOS, so in this case, I assume Shortcuts is running the shortcut remotely on your iPhone. So any problems with that is a problem with Shortcuts.

Thank you for the explanation, eventually I worked around it and just duplicated some shortcuts instead of using a global variable.

Feel free to close the issue if there is nothing you can do about it.

Cheers
