### ISSUE TITLE
Get true file path from share sheet instead of the temp path

### ISSUE THREAD

**Issue by Taxyovio** [sindresorhus/Actions#12]
Currently the Get File Path action returns the temp file path cached by Shortcuts from Share Sheet. Is it possible to grab the real file path instead?

---
Actions 1.5.0 (10) - com.sindresorhus.Actions
iPadOS 15.2
iPad13,11

**Comment by marcusrbrown** [comment]
The temp file path *is* the actual location of the file. It's placed in a temp folder to be visible and readable by the app that receives it. There's no way that Actions or any other non-system app can determine the file source.

**Comment by sindresorhus** [comment]
@marcusrbrown is correct. Only Apple would be able to add this.
