### ISSUE TITLE
com.apple.extensionKit.errorDomain error 2

### ISSUE THREAD

**Issue by wassim01110111** [sindresorhus/Actions#126]
### Description

The following error appears when trying to do any action (com.apple.extensionKit.errorDomain error 2.) rendering the entire thing impossible to use.
![lirlbizddx1b1](https://github.com/sindresorhus/Actions/assets/91387114/0d3547ec-cba7-4e52-8fb7-c177a4127193)

### macOS/iOS version

iOS 16.5

**Comment by sindresorhus** [comment]
Try restarting your device.
