### ISSUE TITLE
Action proposal: Get Host App from Share Sheet

### ISSUE THREAD

**Issue by Taxyovio** [sindresorhus/Actions#13]
Not sure if this is possible. It would be very useful to know from which app the Shortcut Input is shared. 

---
Actions 1.5.0 (10) - com.sindresorhus.Actions
iPadOS 15.2
iPad13,11

**Comment by sindresorhus** [comment]
This is unfortunately not possible, because of restriction in iOS. I recommend submitting a feature request to Apple instead as they are the only ones who could add this.
