### ISSUE TITLE
Action proposal: Modify shortcut name with variable

### ISSUE THREAD

**Issue by shivshankar3578** [sindresorhus/Actions#131]
### Description

Let say my shortcut is to run a script in bash like start a server
but I'd like to know branch name (could be any variable) in shortcut title. (see $x)
  

<img width="594" alt="Screenshot 2023-06-03 at 09 06 44" src="https://github.com/sindresorhus/Actions/assets/10707846/bfbba730-df01-4377-a0b4-b0dc951ea008">

**Comment by sindresorhus** [comment]
There's unfortunately no way to implement this. Only Apple would be able to make such an action. So I recommend sending a feature request to them.
