### ISSUE TITLE
Action proposal: Turn auto-brightness on/off

### ISSUE THREAD

**Issue by hartmaj2** [sindresorhus/Actions#133]
### Description

It would be great to have the possibility to turn on/off the auto-brightness feature on iOS devices. I would use it when I am writing with an Apple pencil on my iPad I sometimes accidentally cover the ambient light sensor so the brightness level starts adjusting. That annoys me a bit because it distracts me from the otherwise paper-like experience.

**Comment by sindresorhus** [comment]
iOS is very locked down. Actions unfortunately cannot modify system settings or other apps.
