### ISSUE TITLE
Action proposal: run another app, signout and signin again -iOS

### ISSUE THREAD

**Issue by P5-2005** [sindresorhus/Actions#134]
### Description

my workflow is like that on iOS side, i have an work app, i need to run it then, choose settings button, then signout button, and signin again, giving user password then signin button,
 i do this like 04 times by day, i need to make this unattended without my interaction, only using shortcuts option 04 times by day

**Comment by sindresorhus** [comment]
iOS is very locked down. Third-party apps like Actions unfortunately have no abillity to do these kinds of things. The app you want to automate would need to provide Shortcut actions for what you need. That's the only way to do this on iOS.
