### ISSUE TITLE
Not sure if it’s an issue. But it’s kinda annoying. 

### ISSUE THREAD

**Issue by longwordwithnospaces** [sindresorhus/Actions#135]
### Description

Your app is amazing!
I love  using it. 

I made a small shortcut that just uses Actions-Authenticate function, then opens another shortcut. 

The main shortcut is a lookup that retrieves values from a dictionary. 

It’s working great.

This is where my little “thing” happens. 

1. I run the “starter” shortcut with authenticate
2. It uses FaceID
3. It attempts to open the lookup shortcut. 
then
4. Opens Actions app. 
5. Opens Shortcuts app. 
6. Runs the lookup shortcut over the top. 

Is # 4, and 5 intended to happen?
Or am I using the functions incorrectly?

### macOS/iOS version

16.5

**Comment by cmolina** [comment]
Is there a way to go back to the original app?
