### ISSUE TITLE
Action proposal: wait x mutes and run other shortcut

### ISSUE THREAD

**Issue by alexey-zaharchenko** [sindresorhus/Actions#139]
### Description

Run other shortcut after waiting x minutes/hours

**Comment by alexey-zaharchenko** [comment]
Thank you for such a fast response 😎. 

I believe you're referring to actions like this:
![image](https://github.com/sindresorhus/Actions/assets/1793816/ff143ded-3ccc-463c-ab47-526861dc8231).
Afaik they have limitations on the wait duration, typically 1-2 minutes at most.

What I'm discussing is a longer use case, such as scheduling a shortcut to run in 10 minutes or 1 hour.

For instance, I want to turn on the air conditioner, wait for 15 minutes, and then turn it off. 

Currently, this can be achieved by emulating cron as demonstrated here: https://www.joshholtz.com/blog/2021/06/23/automating-ios-shortcuts-the-cron-job-way.html. This method involves using a alot of personal automations set to "Time of Day". Another option is Pushcut, but it requires a dedicated iOS device to run its app in the foreground.

**Comment by sindresorhus** [comment]
This is unfortunately not possible because third-party shortcut actions are limited to ~30 seconds of execution.

I have submitted feedback to Apple about this, but nothing has happened: https://github.com/feedback-assistant/reports/issues/364
