### ISSUE TITLE
Action proposal: Limit maximum charging percentage

### ISSUE THREAD

**Issue by noobnooc** [sindresorhus/Actions#14]
### Description

Limit maximum charging percentage by given value to protect the battery life. 

Reference: https://github.com/davidwernhart/AlDente

**Comment by sindresorhus** [comment]
I think it would be better to open an issue on Al Dente for it to provide a Shortcuts action. Actions is a sandboxed app in the App Store and does not have the ability to do what Al Dente does.

However, you could also use https://sindresorhus.com/battery-indicator or https://www.lgerckens.de/shortery/ to get notified when the battery is at a certain percentage and needs to be unplugged. It stop charging automatically though.

**Comment by zecanard** [comment]
macOS 26.4 is finally adding this feature for Macs, along with the corresponding [Shortcuts action](https://github.com/sindresorhus/Actions/issues/221#issuecomment-3910850432):

![Image](https://github.com/user-attachments/assets/13354ed2-eeae-4754-b190-7474117e2a65)
(via [MacRumors](https://www.macrumors.com/2026/02/16/mac-charge-limit-macos-tahoe-26-4/))
