### ISSUE TITLE
Action proposal: Rich Menu (similar to Toolbox Pro)

### ISSUE THREAD

**Issue by NoahKamara** [sindresorhus/Actions#141]
### Description

Actions for showing rich menu using the contact vcard method and handling selection values.
-  Create Menu Item (with emoji, icon, custom image), title & subtitle
- List of Menu Items can be shown using the "choose from list action"
- selection returns a Menu Item object containing the title, subtitle and possibly extra properties

I've already developed a MVP on a local branch and would be happy to implement the action myself

**Comment by sindresorhus** [comment]
Pull request welcome 👍
