### ISSUE TITLE
Action proposal: Local Notifications

### ISSUE THREAD

**Issue by NoahKamara** [sindresorhus/Actions#142]
### Description

- The shortcut app allows users to send a notification but not to specify an URL to open when the notification is tapped

The action could look like this:
Send Notification with `title` and `optional subtitle`
- body
- date
- thread ID (string - allows grouping in notification center - possible alternate name 'groupID')
- tap-url

I'd be happy to implement this if accepted

**Comment by sindresorhus** [comment]
Accepted 👍

**Comment by PyaePhyo8612** [comment]
Backup code

**Comment by sindresorhus** [comment]
Duplicate of #97

**Comment by sindresorhus** [comment]
This is now available in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx And will be available in the next App Store update.
