### ISSUE TITLE
macOS: Actions has vanished from Shortcuts

### ISSUE THREAD

**Issue by workflowsguy** [sindresorhus/Actions#143]
Hello,

I have encountered the same issue as  #117, but on macOS. "Actions" is still installed, but it no longer shows up under "Apps" in Shortcuts. In my workflows that use actions from Actions, they show up as "unknown".

Thanks,
Guy

---
Actions 2.7.0 (45) - com.sindresorhus.Actions
macOS 13.5.1
Macmini8,1

**Comment by sindresorhus** [comment]
Try to restart you device.

**Comment by workflowsguy** [comment]
OK, that worked. Let's hope this was just a one-time issue.

Thanks,
Guy
