### ISSUE TITLE
Get/Set ringer volume

### ISSUE THREAD

**Issue by metbril** [sindresorhus/Actions#147]
It would be nice if the app could provide an action to get or set ringer volume as value between 0 and 1. 

This would for example let me set the ringer to a low value when the Do not disturb focus is activated. 

---
Actions 2.7.0 (45) - com.sindresorhus.Actions
iOS 16.6
iPhone11,8

**Comment by sindresorhus** [comment]
iOS is quite locked down and there's unfortunately no way for a third-party app to do this. Only Apple could make an action for this.
