### ISSUE TITLE
Request: Possible version for ios 15?

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [sindresorhus/Actions#148]
I am stuck on ios 15.3.1 (partially due to the fact that my ipad is jailbroken, and the fact that I want to keep trollstore), which means I cannot use this app. Would it be possible to make version for ios 15? I'm fine if it would require removing some actions from the ios 15 version.

I would also like to know if there is a fork that does this.

**Comment by sindresorhus** [comment]
Sorry, I have no plans to support iOS 15.

https://www.makeuseof.com/how-to-download-older-versions-of-apps-on-older-iphone/

**Comment by ego-lay-atman-bay** [comment]
Well, can you give me the ipa for v1.13.1? Or at least tell me how to build it with github actions (I don't have a mac, so that's the best option for me)?
