### ISSUE TITLE
Is Audio Playing Error

### ISSUE THREAD

**Issue by narwahle** [sindresorhus/Actions#149]
Is Audio Playing returns error: The operation couldn't be completed. (com.apple.ex~ tensionKit.errorDomain error
2.) on iOS 17.

Issue is regrettable on multiple iOS devices and tarted with the mot recent app update.

---
Actions 2.8.0 (46) - com.sindresorhus.Actions
iPadOS 17.0
iPad14,1

**Comment by sindresorhus** [comment]
Restart your device.

**Comment by narwahle** [comment]
Thanks, that's resolved the issue.
