### ISSUE TITLE
Reddit post

### ISSUE THREAD

**Issue by 0507spc** [sindresorhus/Actions#15]
### Description

Hi,

Not a proposal but a quick thanks for the great app! I have posted on Reddit about it (incase there is an influx of users / reports etc):

https://reddit.com/r/shortcuts/comments/rms48u/actions_lots_of_useful_actions_to_add_to/

Not sure if you are on Reddit (so couldn't mention you).

Thanks again for a great app!

**Comment by sindresorhus** [comment]
Thanks for letting me know. I have commented.
