### ISSUE TITLE
Action proposal: Get Folders from Input

### ISSUE THREAD

**Issue by peavine** [sindresorhus/Actions#151]
### Description

I wondered if it would be possible to make a Get Folders from Input action, where the input would be paths from a List action (or a Text action). The current solution is to use a Folder action, which works fine, but there are circumstances where it would simplify matters to set the folders as paths in a List action and then to make the paths into a folder where needed. If it makes a difference, I use Shortcuts on macOS.

Thanks for the great app. I'm new to Shortcuts, but I've already put Actions to work in my shortcuts.

**Comment by sindresorhus** [comment]
Do you need to filter paths that are folders (some paths are files and some are folders and you want the folder paths only) or do you need to get the folders of paths (paths are paths to files and you want the paths to their containing folders)?

If the former, you can use the `Get File Path` action and then filter based on whether the path ends with `/`.

**Comment by peavine** [comment]
Thanks for the quick response. I should have explained better, because I don't believe either of the circumstances you note is what I want to do. I've included a screenshot below that is a very-simplified example. In this example, the first action could be a Folder action but using a list is much easier in the full shortcut.

<img width="657" alt="Actions App" src="https://github.com/sindresorhus/Actions/assets/35905279/04e9cfe2-45a6-4bee-ae5b-845d6a640879">

**Comment by sindresorhus** [comment]
Ah, I understand now. This is not really possible. Only the system would be able to create a folder object from a path (because of sandboxing).
