### ISSUE TITLE
Action Proposal: Checking Ambient Light Level

### ISSUE THREAD

**Issue by lorencerri** [sindresorhus/Actions#153]
### Description

I’m honestly not sure if Apple allows access to sensors like the ambient light level one but it seems super useful for the new action button to see if it’s needed to turn on the flashlight.

**Comment by sindresorhus** [comment]
iOS does actually have an API for this: https://developer.apple.com/documentation/sensorkit/srsensor/3377673-ambientlightsensor

But unfortunately, they only allow its usage for research study apps.

> Apple only grants the entitlement for approved research studies. 
> - https://developer.apple.com/documentation/sensorkit/configuring_your_project_for_sensor_reading

**Comment by DracoClaw** [comment]
it looks like this is no longer limited. can it be added perhaps?

**Comment by sindresorhus** [comment]
It's still limited:

> To use SensorKit, the OS requires the [com.apple.developer.sensorkit.reader.allow](https://developer.apple.com/documentation/BundleResources/Entitlements/com.apple.developer.sensorkit.reader.allow) entitlement in your app’s code signature. Apple only grants the entitlement for approved research studies. If you’re interested in accessing SensorKit data for your study, submit a research proposal and request the entitlement. For more information, see [Accessing SensorKit Data](https://www.researchandcare.org/resources/accessing-sensorkit-data/).
> - https://developer.apple.com/documentation/sensorkit/configuring-your-project-for-sensor-reading?utm_source=chatgpt.com#Request-the-sensor-reader-entitlement
