### ISSUE TITLE
Is Audio Playing broken on iOS 17.0.1

### ISSUE THREAD

**Issue by wzxu** [sindresorhus/Actions#155]
As title. 

![IMG_3848](https://github.com/sindresorhus/Actions/assets/5619348/d6ba701e-3548-4fc7-b964-d43c03c826ae)

---
Actions 2.8.1 (47) - com.sindresorhus.Actions
iOS 17.0.1
iPhone15,2

**Comment by sindresorhus** [comment]
Try to restart your device.

**Comment by wzxu** [comment]
> Try to restart your device.

Thank that fixed it. So it's not a bug of Actions but iOS's problem? I'll close this issue?

**Comment by sindresorhus** [comment]
iOS bug
