### ISSUE TITLE
Action Proposal: Is Orientation Lock On

### ISSUE THREAD

**Issue by guyyst** [sindresorhus/Actions#157]
### Description

This would be identical to existing actions like "Is Silent Mode On", "Is Dark Mode On", etc.

The existing action "Get Device Orientation" is already very useful (thanks for that <3), but I for example, would like the new action button to toggle Orientation Lock, and provide different haptic feedback based on the state that was toggled to.

Edit: Googling around it seems that iOS does not provide an API to get this state, which is disappointing... Would love to be corrected if anyone's finds a way, but it's probably back to writing Feedbacks to Apple and hope this gets natively implemented in 6-7 years :(

**Comment by sindresorhus** [comment]
There's unfortunately no way to get this info. I recommend sending feedback to Apple.
