### ISSUE TITLE
Action proposal: Compare Lists

### ISSUE THREAD

**Issue by josh** [sindresorhus/Actions#16]
It'd be useful to perform some of the fundamental set operations on lists, such as finding the items in both lists or those items that are unique to a single list.

Here's a rough sketch of what I'm thinking:

<img width="1065" src="https://user-images.githubusercontent.com/137/147422960-ca83bb07-d7c5-464e-a12c-f651c6184970.png">

If you think it's generally a good idea, I can push up a PR for further discussion.

Thanks for considering!

**Comment by sindresorhus** [comment]
I think it's a good idea. I was already planning to add something like this.

Pull request welcome :)

---

Make sure you have read https://github.com/sindresorhus/Actions/blob/main/.github/contributing.md
