### ISSUE TITLE
Is Device Locked doesn’t report true when locked

### ISSUE THREAD

**Issue by EthanG45** [sindresorhus/Actions#160]
### Description

Hi! I’ve been testing the new is device locked action, and it doesn’t seem to work as expected. I made an action button shortcut that runs is device locked and sends a notification with the result. When I run it with my phone locked, I get no. I can’t screen record while locked, but here is a screenshot.

![image](https://github.com/sindresorhus/Actions/assets/55003415/d3a7b072-8395-4377-8a18-ac9b690204e3)

### macOS/iOS version

iOS 17.0.2

### Shortcut URL

https://www.icloud.com/shortcuts/78df1f75830d4754a532088497eca303

**Comment by sindresorhus** [comment]
As per the action description, it takes about 10 seconds from you lock your screen until the device is actually locked.

**Comment by EthanG45** [comment]
Whoops that’s a read the manual moment. Thank you!!
