### ISSUE TITLE
Suggestion for Get Boolean from Input action

### ISSUE THREAD

**Issue by tamaracks** [sindresorhus/Actions#162]
I love the Boolean related actions, but it would be handy if Get Boolean from Input could return no value or something else instead of throwing an error that ends the shortcut. That way, the shortcut could decide what to do if no Boolean was found.

**Comment by sindresorhus** [comment]
I agree. That's better behavior. I'll get this fixed in the next update.

**Comment by tamaracks** [comment]
Thanks!
