### ISSUE TITLE
Please support older iOS versions like every other app!

### ISSUE THREAD

**Issue by olivertzeng** [sindresorhus/Actions#165]
As an average redditor on r/jailbreak, we don't upgrade our iOS versions. Can you at least make this app support at least down to iOS 16? I'm currently using iOS 16.5 with iPhone 14 but the minimum iOS version is iOS 16.6![image](https://github.com/sindresorhus/Actions/assets/86348833/71657c15-b84d-456d-a8ee-e33c176ff60b)

**Comment by sindresorhus** [comment]
I target this version to avoid iOS bugs, which creates a lot of extra support for me. You can still press the "get" button and receive an older version though.

**Comment by olivertzeng** [comment]
> I target this version to avoid iOS bugs, which creates a lot of extra support for me. You can still press the "get" button and receive an older version though.

Where is the get button? If I press the get button it will show me that I can't install that app @sindresorhus

**Comment by sindresorhus** [comment]
https://www.makeuseof.com/how-to-download-older-versions-of-apps-on-older-iphone/

**Comment by olivertzeng** [comment]
Thanks @sindresorhus 
As an arch user I'm ashamed that I didn't rtfm and use the search icon

**Comment by olivertzeng** [comment]
I have not installed the app before and don't have an iOS version later than this iPhone what can I do?

**Comment by olivertzeng** [comment]
🙏 managed to do it using your method!
