### ISSUE TITLE
Action proposal: device display’s touch state

### ISSUE THREAD

**Issue by juliusl** [sindresorhus/Actions#168]
### Description

Check and return the touch state of the screen. This could be used with the action button to dynamically switch the function.

For example, with the left hand gripping and thumb holding the action button, based on the touch count of the right hand do x.

Would mostly be useful to know if at least multi-touch is detected but additional information is appreciated.

**Comment by sindresorhus** [comment]
This is unfortunately not possible. Touch can only be detected in an app when it's in the foreground. Only Apple can make an action like this.
