### ISSUE TITLE
Host reachable fails with local IPs

### ISSUE THREAD

**Issue by arpadtomanmarton** [sindresorhus/Actions#174]
### Description

When trying to connect to a local IP with an iPhone, the result of **Is Host Reachable** is always false. In comparison, the same works with a public IP. 

My guess is the app should request access to the Local Network, which is a Privacy & Security option now. Could you please add asking for this permission? 

### macOS/iOS version

iOS 17.0.1

**Comment by arpadtomanmarton** [comment]
I have tested it with the new version (=2.10.0), but the issue still remains and the app is also not showing up under the Local Network menu in the privacy settings :(

**Comment by sindresorhus** [comment]
Try the TestFlight. Should be fixed there. https://testflight.apple.com/join/fJGUrsZx

**Comment by hispeedsurfer** [comment]
Hi, Action is a create shortcuts supplement. 

I also cannot use a local network address in actions like is host/web server reachable. I think there should be the corresponding setting in Info.plist the get the privacy settings for local networks

**Comment by sindresorhus** [comment]
> I think there should be the corresponding setting in Info.plist the get the privacy settings for local networks

https://github.com/sindresorhus/Actions/blob/b8f0425689704e52ee07fc81191cd1c6e6ffc6b0/Actions.xcodeproj/project.pbxproj#L1122

**Comment by hispeedsurfer** [comment]
Ok, I use version 3.1.0 of Actions App on iPad but the are no settings for local network. When I switch to debug in “Is host reachable” I gets “Network.NWError error 50 - network is down”.

**Comment by zecanard** [comment]
I’ve just tried this with v3.1.0 (62), and a 10.0.1.xxx address. I didn’t prompted for Local Network permissions, and the Action returns No, or the error mentioned by @hispeedsurfer with Debug on.

**Comment by hispeedsurfer** [comment]
@sindresorhus Is it working for you on iPhone/ iPad?

**Comment by zecanard** [comment]
I tried under 3.1.1 (65), and Actions prompted me for Local Network access when I launched it. Is Host Reachable then correctly returned Yes on my LAN host.

Thank you 🙏🏼

**Comment by sindresorhus** [comment]
@zecanard Great. Thanks for confirming.

@hispeedsurfer Fixed in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx

**Comment by hispeedsurfer** [comment]
@sindresorhus great work. It’s working on iPhone/ iPad  with local network policy acceptance
