### ISSUE TITLE
Action proposal: Check if Day or Night

### ISSUE THREAD

**Issue by alexclst** [sindresorhus/Actions#18]
Right now we can theoretically use the Weather actions to determine if it is daytime or nighttime, but this involves many different actions and if statements. I actually tried and failed at doing this, plus doing so bloats a shortcut quite a bit. It would be handy to have a single action that can be passed to an if statement that basically checks for it being day or night (based on sunrise and sunset), maybe even other variants.

This could be particularly useful in conjunction with HomeKit actions, or the personal automation capability, to further ensure things only happen, say, at night. I know I could use such a thing in one Home-related shortcut I dream of.

---
Actions 1.5.1 (11) - com.sindresorhus.Actions
macOS 12.1.0
Macmini9,1

**Comment by sindresorhus** [comment]
Sunrise and sunset does not accurately reflect day and night though. For example, some places in Norway, the sun never sets at some parts of the year.

Can you be more specific what you need this for? If it's just whether it's night or day, it's better to define a certain time that's considered day and night.

**Comment by alexclst** [comment]
I was just thinking about is it dark outside or not. This is what we can do with a string of actions right now, but which a single action that can say that may be easier to deal with. However, you're suggestion isn't a bad one, it is just that the actual split between light and dark changes throughout the year.

**Comment by sindresorhus** [comment]
Not sure why you are closing. I was not declining this. Just trying to make sure we are solving the correct problem.
