### ISSUE TITLE
Get Current Noise Control mode (Transparency/Adaptive/Noise Cancellation)

### ISSUE THREAD

**Issue by kitsah** [sindresorhus/Actions#182]
### Description

My proposed action will get the current noise control mode of connected AirPods, so I know if currently using Transparency, Adaptive, Noise Cancellation or Off.

I want to make an iPhone 15 Pro Action Button shortcut which cycles through the noise control modes and to do this I need to know the current noise control mode so I know which one is next in the cycle.

**Comment by sindresorhus** [comment]
This is unfortunately not possible. I encourage you to send feedback to Apple about making an action for this: https://feedbackassistant.apple.com
