### ISSUE TITLE
Action proposal: Floating Choose From List (Extended)

### ISSUE THREAD

**Issue by mkozjak** [sindresorhus/Actions#184]
### Description

Hi!

Is there a way to make Choose From List (Extended) to _float_ just like it's implemented here with stock Choose From List using vcard?

![image](https://github.com/sindresorhus/Actions/assets/3506172/cc38e9af-18a2-4934-afa5-7f3f1b6eab02)

This implementation seems to fill the entire screen with the menu and takes substantial amount of space for just three lines, in my case.

Thanks for working on this code! It's amazing!

**Comment by sindresorhus** [comment]
Unfortunately not possible.
