### ISSUE TITLE
Is Watch Connected? (Boolean)

### ISSUE THREAD

**Issue by scornfulMussel6** [sindresorhus/Actions#191]
### Description

Consider an action step that provides a Boolean on whether an Apple Watch is connected to the device. This would only work on iPhone, presumably. It would also for “is watch on?” to be part of a condition to run parts of a shortcut.

**Comment by sindresorhus** [comment]
This is unfortunately not possible. Only an app that also has a watch app (which Actions does not) can check the connection status of a watch. I encourage you to send feedback to Apple about making such an action: https://feedbackassistant.apple.com/
