### ISSUE TITLE
Truncate action causing "This action is trying to share 10016005571271983104 Finder items, which is not allowed." error

### ISSUE THREAD

**Issue by chrisgrande** [sindresorhus/Actions#201]
Setup: a folder of 150 PDFs, For Each Loop, Truncate the files Name to any number of characters, causes the error "This action is trying to share 10016005571271983104 Finder items, which is not allowed.". 

Enabling the "Allow sharing large amounts of data" setting mitigates the issue.

https://github.com/sindresorhus/Actions/assets/825577/d0ad3e48-6dc4-4e42-ac4d-fd7535243ef8

---
Actions 2.10.0 (51) - com.sindresorhus.Actions
macOS 14.2.0
Mac14,12

**Comment by sindresorhus** [comment]
The message is shown because you are techincally sharing large amounts of data with the Actions app. There's no way around this.

**Comment by chrisgrande** [comment]
Certainly not that amount of items, I'm guessing the error count calculation is a bug of some sort with Shortcuts.
