### ISSUE TITLE
Action proposal: Is HomeKit accessories not responding

### ISSUE THREAD

**Issue by alferd4829** [sindresorhus/Actions#202]
### Description

To identify HomeKit accessories is on not responding mode

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/Actions/issues/66

I don't plan any HomeKit actions.

You could also try requesting it here: https://apps.apple.com/us/app/homebot-for-shortcuts/id1553547811

**Comment by alferd4829** [comment]
Thank you for your suggestion
