### ISSUE TITLE
does not run when locked

### ISSUE THREAD

**Issue by rmichelena** [sindresorhus/Actions#203]
### Description

I tried to use Actions (specifically, the "ask for text with timeout" one) on a Shortcut that is run via automations, so in other words sometimes it runs when the iPhone is locked... and in that case, it errors out with _The request to open "com.sindresorhus.Actions" failed_ ; so no way around this?

### macOS/iOS version

iOS 17.1

**Comment by sindresorhus** [comment]
The action needs to open the Actions app to show the user-interface to provide input, and it cannot open when the device is locked. There's no possible workaround.

**Comment by rmichelena** [comment]
So other actions of the Actions app, those that do not require user interface, can run via automations even when the iPhone is locked?

**Comment by sindresorhus** [comment]
Yes
