### ISSUE TITLE
Deactivate tap to wake  when phone upside down in pocket 

### ISSUE THREAD

**Issue by emmgr23** [sindresorhus/Actions#205]
### Description

Hi, I'm not sure if this is possible, but I think it would be very useful. I often turn on by mistake the light, the camera, or  now the new menu to personalize the home wallpaper when my phone is in my pocket. and I'm sure I'm not the only one. Do you think it's possible to deactivate the tap-to-wake function when the phone is upside down in the pocket or activate tap-to-wake only when the phone is in a portrait position?

**Comment by sindresorhus** [comment]
This is unfortunately not possible
