### ISSUE TITLE
Action proposal: Current Elevation

### ISSUE THREAD

**Issue by zecanard** [sindresorhus/Actions#207]
### Description

Would it be possible for Actions to query the current elevation? All iPhones starting with the 6 series have a barometric altimeter, and older ones provide GPS-based altitude.

Thank you!

**Comment by sindresorhus** [comment]
I will add it in the next update 👍

**Comment by zecanard** [comment]
You rock! 🙌🏼

**Comment by zecanard** [comment]
Looks to be working well! Thank you.

Although the units need to be filtered, I think 🤔

![IMG_8711](https://github.com/sindresorhus/Actions/assets/25799849/12e74f39-3d6c-41ef-9798-6165895d9b67)

**Comment by sindresorhus** [comment]
> Although the units need to be filtered, I think 🤔

The action returns the correct unit, so this is just another Shortcuts bug.

**Comment by zecanard** [comment]
This Action kept timing out when I tried it today, a few hours after restarting my iPhone. I opened the Compass app, and the Action immediately started working.

This hadn’t happened before, even though I don’t open the Compass very often, so I’m not sure what else starts up the altimeter (maybe Maps). Just a heads up.

Thanks again for implementing this!

**Comment by zecanard** [comment]
This actually happens every time I reboot my iPhone: Get Elevation times out after ≈ 30s. Opening the Compass app does allow the Action to complete, but only for a few seconds. If I wait and try again, the Action times out again.

The issue may persist for many hours (6+ hours in my experience), and I haven’t been able to determine what gets the Action working again. I live on the second floor of a building, and in my (very limited) observations it has started working every time I went downstairs. Butit has also started working despite not leaving my apartment.

I’m not sure if this is caused by iOS 17.4, but I don’t recall it happening on 17.3. Is there anything the app can do to trigger the altimeter?

![New Shortcut](https://github.com/sindresorhus/Actions/assets/25799849/75923b9d-1f00-4516-b32a-797ac45d18ff)

**Comment by zecanard** [comment]
This bug persists in 17.4.1, but my report from February got updated today. When I checked this morning, it was Open with more than 10 similar reports; tonight it’s showing a fix is coming.

![Screenshot 2024-03-29 at 23 04 14](https://github.com/sindresorhus/Actions/assets/25799849/b846058f-a32c-45b5-8e2b-fc334a9b956b)

**Comment by zecanard** [comment]
I believe this was finally fixed at some point during the iOS 18.0 beta cycle.
