### ISSUE TITLE
Action proposal: set volume bluetooth speaker

### ISSUE THREAD

**Issue by rlb222** [sindresorhus/Actions#208]
### Description

When I set the volume with a shortcut while my stereo is playing via Bluetooth or airplay, the volume is not changed. 
only the volume of the iPhone is changed. 

It would be great to have an action that can alter the volume of the connected music playing device.

**Comment by sindresorhus** [comment]
This is unfortunately not possible. I encourage you to send feedback to Apple about it: https://feedbackassistant.apple.com

**Comment by rlb222** [comment]
Thank you! I will. René —//—Op 22 dec 2023 om 15:38 heeft Sindre Sorhus ***@***.***> het volgende geschreven:﻿
This is unfortunately not possible. I encourage you to send feedback to Apple about it: https://feedbackassistant.apple.com
