### ISSUE TITLE
"Is Silence mode On" always returns true on iphone15pro@ios17.2

### ISSUE THREAD

**Issue by manuhank** [sindresorhus/Actions#209]
Regardless if of the silence mode status, the action will always return true.

**Comment by sindresorhus** [comment]
What device? And make sure you read the known limitation in the action description.

**Comment by alferd4829** [comment]
There is no such issue on my iPhone 15 pro max 17.2.1

**Comment by manuhank** [comment]
> What device? And make sure you read the known limitation in the action description.

I see the problem. The limitation mentions voice notes recording, but this seems to also apply to the camera app, even if it's in photo mode.

As mentioned in the op the device is the iPhone 15 pro, and the repro steps is to have a open camera as the trigger of a shortcut that read is silent mode on.
