### ISSUE TITLE
Action proposal: get location as a Geo URI

### ISSUE THREAD

**Issue by hacdias** [sindresorhus/Actions#21]
### Description

Hi! I'd like to propose an action to get the user's location as a Geo URI string: `geo:{lat},{lon};`. This is possible to do via a sequence of other actions, but I think it'd be a great addition for this app!

**Comment by sindresorhus** [comment]
I think it would be better if the actions accepts a location and generates the Geo URI from it. That way it's more flexible. It also means the Actions does not have to ask for location permission. I'll get to this soon.

**Comment by sindresorhus** [comment]
There's an update out now with this: https://apps.apple.com/no/app/actions/id1586435171
