### ISSUE TITLE
Connect to Bluetooth device

### ISSUE THREAD

**Issue by nightah** [sindresorhus/Actions#211]
### Description

The intent of this action is to provide a means to connect to a Bluetooth device (not a speaker) which already has been paired to your phone.

I understand that you can use the native set playback destination to achieve this goal for Bluetooth speakers by the device in question I would like to use this for is not a speaker.

Just to be clear this isn’t to connect to a device that the phone has never dealt with before.
it’s just to reestablish a connection to a previously trusted device.

**Comment by sindresorhus** [comment]
This is unfortunately not possible. Actions cannot affect the system connection status of a Bluetooth device. I encourage you to send feedback to Apple about making an action for this: https://feedbackassistant.apple.com
