### ISSUE TITLE
Enhance existing Action: Get Music Playlists (iOS Only)

### ISSUE THREAD

**Issue by jsiegenthaler** [sindresorhus/Actions#212]
### Description

I use the **Get Music Playlists (iOS Only)** action
I auto-create playlists monthly and weekly. I would like to find the most recently created playlist, and I can find no simple way to sort by Date Created.
Can you please add these options to this action:

- Sort by Name/Created Date/Last Played date (only if possible) 
- Order Ascending/Descending
- Limit On/Off
- Maximum Results (integer, shown only when Limit is shown)

Many thanks

**Comment by sindresorhus** [comment]
I added a new action called “Find Music Playlist” in the latest TestFlight build which included what you requested: https://testflight.apple.com/join/fJGUrsZx

**Comment by jsiegenthaler** [comment]
Action works well, thanks
