### ISSUE TITLE
Action proposal: Is External Display Connected?

### ISSUE THREAD

**Issue by mhwice** [sindresorhus/Actions#219]
### Description

I would like to see an _Is External Display Connected_ or _Count of External Displays_ action. 

This would allow me to have an automation using Shortery that turns on my office lights only when my Mac wakes from sleep and is connected to power and is connected to my monitor. Thanks!

**Comment by sindresorhus** [comment]
You can already do this with the built-in actions: https://www.icloud.com/shortcuts/1f9fb9c1945f4a1a89d5a6765e8cc874
