### ISSUE TITLE
Action proposal: Shortcut to open selected file/folder with a given application?

### ISSUE THREAD

**Issue by wilky761** [sindresorhus/Actions#22]
### Description

Hi there,

I'd like to be able to have a shortcut that can do the following:

I have selected a file or folder in both the Finder or Path Finder apps.  I want to be able to use a shortcut to open the file or folder with the given app (for example, the app Meta). This global shortcut would need to be connected to this action (and given app). I can't find this shortcut anywhere.

<img width="780" alt="Screenshot 2022-02-27 at 13 16 47" src="https://user-images.githubusercontent.com/74021414/156398622-85d435d0-a5d6-41f1-90f3-175f7911b82d.png">
.

**Comment by sindresorhus** [comment]
Like this? https://www.icloud.com/shortcuts/8bb832c15fb94bed9cfd6f265efb0d61

**Comment by wilky761** [comment]
Thank you. 

Yes, this is what I was after, although seems it cannot be replicated for the app I regularly use (Path Finder) which is a shame. And I can't see any workaround to make it work under Path Finder.

Appreciated.

**Comment by vorodo** [comment]
Try identifying the app by its bundle ID rather than its name. Type this in the terminal to get the bundle id: osascript -e 'id of app "Path Finder"'

**Comment by wilky761** [comment]
Thank you. the bundle id is:

"com.cocoatech.PathFinder"

But I'm not really sure what I can do with that. I tried typing this into the Shortcuts app and it brings up nothing. So I guess there is no way of getting Path Finder to "play nicely" with Shortcuts.

**Comment by vorodo** [comment]
Whereas the first image below uses the app name (and can't find the application, so it opens a window for the user to select the application), the second image below uses the bundle id, which is recognized by shortcuts and opens sublime with a new text file entitled 'My text file.txt.' If the application isn't opening, the problem can likely be resolved by using the bundle ID in place of the name. If the application is opening but doesn't know what to do with the file being transferred to it, it's less likely using the bundle ID will help.
![Screen Shot 2022-03-03 at 12 50 39 PM](https://user-images.githubusercontent.com/85590914/156652155-d426c68d-6bbb-4051-aa7d-4f1b23a82303.png)
![Screen Shot 2022-03-03 at 12 50 04 PM](https://user-images.githubusercontent.com/85590914/156652161-be333fcc-fd65-46a8-929c-7cc6a3eafcca.png)

**Comment by wilky761** [comment]
I see. TBH, I've no idea how you even managed to get those screens. I'm a newbie when it comes to shortcuts and I don't even know what sublime is, but thanks for trying to help :)

**Comment by wilky761** [comment]
Why was this closed as my request wasn't resolved? Thanks.

**Comment by vorodo** [comment]
> I see. TBH, I've no idea how you even managed to get those screens. I'm a newbie when it comes to shortcuts and I don't even know what sublime is, but thanks for trying to help :)

No problem, try this: [Shortcut iCloud Link.](https://www.icloud.com/shortcuts/303c03d16c6d427b86b70b9f3472cc64) If this doesn't work, I wouldn't know what to try next. I believe he closed it because there's already built in functionality by apple to accomplish what you'd like. Either there's a bug on the part of Apple, or something PathFinder is doing that is making the action incompatible. Those would be the parties best suited to fix the issue.

**Comment by wilky761** [comment]
Thanks for giving it a go, and yes, it seems to be an issue with Pathfinder as still seeing the error as per the screen grab. 

<img width="911" alt="Screenshot 2022-03-04 at 16 57 07" src="https://user-images.githubusercontent.com/74021414/156806264-22f96f90-ac28-4d1c-bf59-08e797aadb30.png">
