### ISSUE TITLE
Action proposal: set battery charging optimization config

### ISSUE THREAD

**Issue by jlaffaye** [sindresorhus/Actions#221]
### Description

Set the battery `Charging optimization` config to :
- `Optimized`
- `80% Limit`
- `None`

Use case: when connected to carplay, set it to `80% Limit`
when disconnected from carplay, set it to `Optimized`

**Comment by sindresorhus** [comment]
This is unfortunately not possible. iOS is quite locked down, and changing things in the system is generally not possible. I encourage you to send feedback to Apple about it: https://feedbackassistant.apple.com

**Comment by zecanard** [comment]
Apple is adding this action in iOS 26.4, although it doesn’t allow changing the Optimized toggle.

<img width="660" height="634" alt="Image" src="https://github.com/user-attachments/assets/eea4f87c-7430-4bc4-b671-f5e8a61d7840" />
