### ISSUE TITLE
Action proposal:  Universal back button? Turn off screen? 

### ISSUE THREAD

**Issue by kizovinh** [sindresorhus/Actions#222]
### Description

Is there any possibilities to create an universal back button like android does, and turn off the screen with shortcut? 

Currently native support is lock srcreen and shutdown only. 

Very good app, appreciate!

**Comment by sindresorhus** [comment]
> Is there any possibilities to create an universal back button like android does,

iOS has no universal notion of "back", so even Apple would not make an action for this.

> and turn off the screen with shortcut?

This is unfortunately not possible. I encourage you to send feedback to Apple about making an action for this: https://feedbackassistant.apple.com
