### ISSUE TITLE
Action proposal: Join Wifi Action

### ISSUE THREAD

**Issue by Rihcus** [sindresorhus/Actions#223]
### Description

Give an action that allows user to input a wifi ssid and password to trigger join wifi prompt. Uses NEHotspotConfigurationManager

https://developer.apple.com/documentation/networkextension/nehotspotconfigurationmanager

https://forums.developer.apple.com/forums/thread/111307

**Comment by Rihcus** [comment]
![IMG_0757](https://github.com/sindresorhus/Actions/assets/30292597/c0b5d097-3bce-47a9-a7d9-22db764f7cf0)

Example

**Comment by sindresorhus** [comment]
I added this in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx

**Comment by Rihcus** [comment]
It works. Out of curiosity is there any reason the join Wi-Fi action opens the action app first before prompting the join option.

**Comment by sindresorhus** [comment]
It's explained in the action description.

**Comment by Rihcus** [comment]
Do you have any issues with disconecting wifi? I tested it with a hotspot on my phone and I noticed after connecting it gets disconnected within a few seconds.

On the other hand if I try joining the hotspot via control center wifi menu or settings wifi menu I don't experience disconnections.

One other strange thing I noticed is if I create a shortcut that runs the join wifi action with wait for connectin setting off and have a open actions app acction:

![IMG_D7F9B867DF35-1](https://github.com/sindresorhus/Actions/assets/30292597/3fa53560-655c-4e00-9bda-f9f038630397)

If I wait to for the above shortcut to finish then click "join" the network will stay connected as long as the actions app is kept open. However when you leave the app within 20 seconds the network will disconnect.

iPadOS Version: 17.3.1
Actions app Version: 3.1.1 (66)

**Comment by Rihcus** [comment]
> Do you have any issues with disconecting wifi? I tested the action with a ipad with and a hotspot hotspot on my android phone and I noticed after connecting the ipad gets disconnected within a few seconds.
> 
> On the other hand if I try joining the hotspot via control center wifi menu or settings wifi menu I don't experience disconnections.
> 
> One other strange thing I noticed is if I create a shortcut that runs the join wifi action with wait for connectin setting off and have a open actions app acction:
> 
> ![IMG_D7F9B867DF35-1](https://private-user-images.githubusercontent.com/30292597/304142060-3fa53560-655c-4e00-9bda-f9f038630397.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTMzNTksIm5iZiI6MTcwNzc1MzA1OSwicGF0aCI6Ii8zMDI5MjU5Ny8zMDQxNDIwNjAtM2ZhNTM1NjAtNjU1Yy00ZTAwLTliZGEtZjlmMDM4NjMwMzk3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNTUwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmQ0MDc5YjEyZjVhZjUwMGNmZGU4N2FmNDEyMDg4MDc2ZDkxNjQxZGI0YjRkZTFlZGU2Zjg3NGMyZDMxNzlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gxUEwvRQVNzREYCyzPdJKF2iT9_qI9T4I8WTuirrT7k)
> 
> If I wait to for the above shortcut to finish then click "join" the network will stay connected as long as the actions app is kept open. However when you leave the app within 20 seconds the network will disconnect.
> 
> iPadOS Version: 17.3.1 Actions app Version: 3.1.1 (66)

Also not sure if this should be moved to a bug report

**Comment by sindresorhus** [comment]
@Rihcus Should be fixed in the latest TestFlight build (67).

**Comment by Rihcus** [comment]
> @Rihcus Should be fixed in the latest TestFlight build (67).

Thanks for the fix, bug is gone 👍
