### ISSUE TITLE
Action proposal: Set orientation possible? Run custom gestures? 

### ISSUE THREAD

**Issue by kizovinh** [sindresorhus/Actions#224]
### Description

I would like to make a shortcut to switch between portrait and landscape mode, is it possible? 

And I also want to run some custom gesture, for example open an app then tap an item, is that possible either?

**Comment by sindresorhus** [comment]
This is unfortunately not possible. I encourage you to send feedback to Apple about making an action for this: https://feedbackassistant.apple.com
