### ISSUE TITLE
Action proposal: Pass Settings to iPhone Document Scanner

### ISSUE THREAD

**Issue by jmediadesign** [sindresorhus/Actions#226]
### Description

Is it possible to allow control of iPhone Document Scanner settings from the shortcut, such as File Type, Auto/Manual, etc?

My current use case is to default to Manual rather than Automatic, and at the moment I have to quickly tap that setting in iPhone as the process is running.

**Comment by sindresorhus** [comment]
This is not possible. The action uses iOS's document scanner component, and it's not configurable. To choose file type, you can just use the built-in image converter action.
