### ISSUE TITLE
Bug with "ask for text with timeout"

### ISSUE THREAD

**Issue by kuitog** [sindresorhus/Actions#229]
### Description

I have an automation where if I plug my charger it asks me if I want to open google maps. The default answer is "Yes"

Desired behaviour:
The input window pops up, I press enter if I want to open gmaps or I just let it expire if I don't want it. So pressing enter I should get "yes" in the clipboard.

The problem:
If I configure a default answer ("yes") and click ok when the window pops up without modifying the answer I get a blank clipboard. Only if I add or remove a character then the clipboard is populated.

### macOS/iOS version

17.3.1

**Comment by sindresorhus** [comment]
Works fine for me: https://www.icloud.com/shortcuts/a02c49fbf647462cb02f8412e500237f

![IMG_206613908650-1](https://github.com/sindresorhus/Actions/assets/170270/6530099e-52f0-4186-800e-4ee565a85e4e)

**Comment by kuitog** [comment]
Yep, that works for me as well. Also if I create a new shortcut it works now.

But take a look at this, still doesn't work:
https://www.icloud.com/shortcuts/471db97e0a1140e49cdbf3060dd79a3f

Maybe because the buggy verdion was created  before restarting the phone just after installation?
________________________________

**Comment by kuitog** [comment]
Wait! I figured it out. If you add a timeout timer then it doesn't work in any shortcut including yours

**Comment by sindresorhus** [comment]
Should be fixed now in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx

**Comment by kuitog** [comment]
Nice! Thanks! Do you have an expected release for the app store version?
________________________________

**Comment by kuitog** [comment]
Thanks :)
________________________________
