### ISSUE TITLE
Parse JSON

### ISSUE THREAD

**Issue by xplosionmind** [sindresorhus/Actions#23]
### Description

Since in 1.8.0 the wonderful feature of “Parse CSV” has been added, I think it would be extremely useful to provide one identical action, that parses JSON instead.

**Comment by sindresorhus** [comment]
Shortcuts already supports JSON natively: https://support.apple.com/en-ca/guide/shortcuts/apd0f2e057df/ios

**Comment by xplosionmind** [comment]
Thank you for pointing that out! Nevertheless, the link you shared explains how JSON works and what it is, not *how* it works in Shortcuts.

If I search for “JSON” in Shortcuts, I get nothing as a result.

**Comment by sindresorhus** [comment]
I guess it could be better documented by Apple. When you import a JSON into Shortcuts, it is a "List" or "Dictionary" depending on whether the JSOn is an array or object. You can use any List/Dictionary action to get the values.
