### ISSUE TITLE
Set Creation and Modification Date of File

### ISSUE THREAD

**Issue by ruiddevil** [sindresorhus/Actions#236]
In this action I have identified two issues:
1) When modify original option is OFF, the output file for the next action does not have the new date.
2) When modify original date is ON, some video files are not updated in file system. In this case I could not identify a pattern.

My use case is exporting from Photos to Files using the action "Find Photos" and apply a new date from action "Get dates from" that I have confirmed that the date output is correct.

I have iOS 17.4.1 (iPhone 15 Pro Max), using the latest available Actions app version.

**Comment by sindresorhus** [comment]
Make sure you read the action description. There are some known limitations.

**Comment by sindresorhus** [comment]
1. I just tried and it sets the date for me. However, the action cannot guarantee that following actions also preserve the creation date.

**Comment by ruiddevil** [comment]
Not working for me...
1) "Get contents of folder" action
2) "Filter" action
3) this action
4) "Save" action, of the output file to Photos recents
The file added to Photos does not have the updated date.

**Comment by sindresorhus** [comment]
The Photos app reads the capture date from the image metadata, not from the file created/modified date.

**Comment by ruiddevil** [comment]
Actually it appears that it reads both... if there is no EXT info for the date taken of the photo it uses the file dates. But it explains what's happening...
Thank you for the quick replies!
