### ISSUE TITLE
Action proposal: Scan QR Code from Image

### ISSUE THREAD

**Issue by uetchy** [sindresorhus/Actions#24]
### Description

iOS Shortcuts does offer `Scan QR Code` but does not accept image input. This `Scan QR Code from Image` will enable us to scan any QR codes from Photo albums and from Share Extension.

<img width="316" alt="Screen Shot 2022-01-20 at 16 38 39" src="https://user-images.githubusercontent.com/431808/150294651-6d338cf1-0ebe-4f3c-8f10-b79755250671.png">

Actually, I've already implemented it and it's (almost) ready for a PR; I'd like to know if this action is good enough to be included in Actions.

**Comment by sindresorhus** [comment]
Pull request welcome. Make sure you read and adhere to: https://github.com/sindresorhus/Actions/blob/main/.github/contributing.md#submitting-a-new-action
