### ISSUE TITLE
 Last version for iOS 15?

### ISSUE THREAD

**Issue by chr0max** [sindresorhus/Actions#243]
### Description

Answer to this: https://github.com/sindresorhus/Actions/issues/235

![IMG_EF2942CDBE57-1](https://github.com/sindresorhus/Actions/assets/16835263/0d97fadc-c70b-4b2f-858f-7f46b5655e31)

Maybe you have to allow old versions!?

You should do it, its better for anyone without the new hot stuff. I don´t need it anymore. 

### macOS/iOS version

15

**Comment by sindresorhus** [comment]
> Maybe you have to allow old versions!?

All the old versions are set to be allowed to download, so that's not the issue.
