### ISSUE TITLE
Precision in Geo URI

### ISSUE THREAD

**Issue by hanche** [sindresorhus/Actions#244]
### Description

This is a _minor nit_, but here goes anyway:

The geo URI generator produces 15 decimals (meaning digits after the decimal point) for latitude and longitude. That is a precision of roughly an ångström (0.1 nm) – more or less the diameter of a hydrogen atom.

It is especially jarring to see that along with a stated accuracy of 100 meters!.

Ideally, I think it should use as many decimals as implied by the provided accuracy, plus one. So eight decimals for one meter, going into the decimeter range.

In case it matters, when I saw this, the location came from the builtin “Get current location” action.

### macOS/iOS version

iOS 17.4.1

**Comment by sindresorhus** [comment]
This is available in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx
