### ISSUE TITLE
Get Unsplash Image: 503 Error

### ISSUE THREAD

**Issue by spenpal** [sindresorhus/Actions#248]
### Description

Running the “Get Unsplash Image” action gives the following error: **Request failed: service unavailable (503)**

![IMG_4071](https://github.com/sindresorhus/Actions/assets/44354599/27844d9b-8ea5-4583-b3bc-2b3dc58e3829)

### macOS/iOS version

iOS 17.4.1

### Shortcut URL

https://routinehub.co/shortcut/13484/

**Comment by rastafaa** [comment]
I happened to try this action today and it’s a 404 error every time. Definitely not functional currently.
