### ISSUE TITLE
Action proposal: Close Today View [iOS/iPadOS]

### ISSUE THREAD

**Issue by FelipeRearden** [sindresorhus/Actions#250]
### Description

Hello  @sindresorhus !!!!

My Action Proposal is about a new shortcut action to manage the iOS/iPadOS **Today View** 

> Today View is the name of the window that appears when you swipe right from the left edge of the Home Screen, then scroll up and down.

📷 My Today View
![IMG_0038](https://github.com/sindresorhus/Actions/assets/85180696/4461a194-ce25-41ca-a851-75b3aff288ac)

As you can see from the image I run a lot of Shortcuts from this view to save some space from my **Home View**

### Running Shortcuts from Today View

The problem between Today View and Shortcut Widgets is that I can't close/hide the Today View while running a shortcut.

In other words, when I return to the iOS main screen the Today View is still open instead of the Home View. This way I have to manually swipe left to hide the today view again. 

I tried to solve this issue by using the native action **Go to Home Screen** but unfortunately, does not close/hide the Today View.

### My FR

A new action that closes the Today View. That is it 🙏

If you want to solve all issues from this feature would be 3 new actions:
- Open Today View
- Close Today View
- Toggle Today View 

Maybe this information might be useful: the shortcut action that I am requesting in this FR is the same behavior that we have when hitting <kbd>⌘H</kbd> on iPadOS using an external keyboard 

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by sindresorhus** [comment]
This is unfortunately not possible. I encourage you to send feedback to Apple about making an action for this: https://feedbackassistant.apple.com
