### ISSUE TITLE
"Merge Dictionaries" Action: Feature Upgrade

### ISSUE THREAD

**Issue by spenpal** [sindresorhus/Actions#251]
Instead of listing out all 10 dictionaries as parameters, have a "+" button, whenever you want to add another dictionary. Kind of like the URL action.

Removes redundant space.

![image](https://github.com/sindresorhus/Actions/assets/44354599/317f1d01-3328-4e1f-a4b8-14cdf54ea4c6)

**Comment by sindresorhus** [comment]
It's done like this because the Shortcuts app crashes if I specify it as a list of dictionaries. Maybe if Apple fixes that bug at some point, but it's been years, so I'm not holding my breath.

**Comment by spenpal** [comment]
Thanks for letting me know! That's unfortunate to hear.
