### ISSUE TITLE
How to: randomly select one item from list

### ISSUE THREAD

**Issue by mearleycf** [sindresorhus/Actions#254]
What I'm hoping to do is to set up a list of strings, say 5 strings for starters. Then be able to automate an action that selects, randomly, one string from the list and performs an action on it--say, send a text to a specific recipient. 
It seems like this would be possible, but I'm hoping someone could guide me on the specifics of making it happen?

**Comment by sindresorhus** [comment]
I would recommend asking in https://www.reddit.com/r/shortcuts/ instead. You are more likely to get a good answer there.
