### ISSUE TITLE
Possibly add a shutdown action

### ISSUE THREAD

**Issue by TheDarknessSurroundsYou** [sindresorhus/Actions#258]
The built in shutdown action prompts the end user before shutting down, it would be nice if you could include a action that does not do that

---
Actions 3.3.0 (74) - com.sindresorhus.Actions
iOS 17.5.1
iPhone14,8

**Comment by sindresorhus** [comment]
This is unfortunately not possible. I encourage you to send feedback to Apple about making an option in the built-in action to not prompt: https://feedbackassistant.apple.com
