### ISSUE TITLE
Ordinal Number/Word Conversion

### ISSUE THREAD

**Issue by betafruit** [sindresorhus/Actions#259]
### Description

The spell-out number action is helpful, but it would be nice if it could also convert numbers to their ordinal numeric forms (1st, 2nd, 5678th…) and their ordinal word forms (first, second, five thousand six hundred seventy-eighth…).

**Comment by rastafaa** [comment]
I was just looking for this yesterday, ended up using someone’s shortcut to do it instead

https://www.icloud.com/shortcuts/5a7d5c557db44f9fba85c10b68b413f1

**Comment by sindresorhus** [comment]
This is now available in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx And will be available in the next App Store update.

I decided not to do the "and their ordinal word forms" part as it's complicated and too niche.
