### ISSUE TITLE
Action proposal: Rename a multiple files.

### ISSUE THREAD

**Issue by Chrispy-max** [sindresorhus/Actions#262]
### Description

I built an automation using Automator. Very simple - it creates a host of prenamed job folders - around 150. Some of these folders are partially renamed based on user prompts  - Job No & Client. I'm trying to rebuild the app in Shortcuts, however there's no option to rename multiple folders like Automator, so I'd love to have an action that does this.

**Comment by sindresorhus** [comment]
This is already possible in Shortcuts. Just use the "Rename File" action in a "Repeat" action.
