### ISSUE TITLE
Enhancement suggestion: Support "on" and "off" as text input options in GetBooleanFromInput

### ISSUE THREAD

**Issue by ari-abendstern** [sindresorhus/Actions#264]
When making API calls to Home Assistant their so-called boolean values are returned as "on" or "off" strings. I'm guessing that (although unusual) there are other services that do the same. It would be great to be able to convert these to booleans without using my current workarounds

**Comment by sindresorhus** [comment]
This is supported in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx

**Comment by sindresorhus** [comment]
Now also available in the latest App Store release.
