### ISSUE TITLE
Action proposal: Set Charging Optimization

### ISSUE THREAD

**Issue by gadric** [sindresorhus/Actions#265]
### Description

I am currently traveling a lot because of work. When I am at home, setting battery charging optimization to 80% is sufficient. However, if I am traveling, then I would like to set the Charging optimization to „optimized battery charging“ so I can get to 100% to have enough power for the whole day. 

I can do this based on the location but I have not found a way to set the battery optimization settings.

**Comment by sindresorhus** [comment]
This is unfortunately not possible. I encourage you to send feedback to Apple about making an action for this: https://feedbackassistant.apple.com
