### ISSUE TITLE
Suggestion: make the “Set Uniform Identifier” action work with multiple files

### ISSUE THREAD

**Issue by atnbueno** [sindresorhus/Actions#266]
Right now we can do file by file with a loop:
<img width="686" alt="image" src="https://github.com/user-attachments/assets/95f537d1-859c-4b05-a4fd-bfe1cb3c5d26">

It would be nice if the action accepted multiple files as input and we could skip the loop.

**Comment by sindresorhus** [comment]
Will do it in the next update 👍

**Comment by martindb1988** [comment]
Amazing, looking forward to this 😃

**Comment by sindresorhus** [comment]
Available in the latest App Store release.
