### ISSUE TITLE
3.4 beta global variables bug

### ISSUE THREAD

**Issue by rastafaa** [sindresorhus/Actions#271]
### Description

Submitted via TestFlight but I forget whether you see those or not. There’s a new bug preventing global number variables from being set.. and maybe others too? Not sure. I’ll restart and update this if it works after

Edit; restarted and still seeing same error

downgraded and it works now 

![IMG_8608](https://github.com/user-attachments/assets/2479e5e4-e423-4f69-8225-2f633a56d2e2)
![IMG_8609](https://github.com/user-attachments/assets/891970a3-5bad-4b84-a6ef-1fbbba127cbc)

### macOS/iOS version

17.5.1

**Comment by sindresorhus** [comment]
Fixed in the latest TestFlight update (build 80).
