### ISSUE TITLE
Get status of Hotspot Connections

### ISSUE THREAD

**Issue by falkaabi** [sindresorhus/Actions#273]
### Description

I would like to use this to Turn Personal Hotspot on until all connected devices disconnect, then turn it off along with wifi to preserve phone battery. Currently there is no way to check whether Personal Hotspot is on or off, can only turn it on/off or toggle it with builtin actions.

**Comment by sindresorhus** [comment]
This is unfortunately not possible. I encourage you to send feedback to Apple about making an action for this: https://feedbackassistant.apple.com
