### ISSUE TITLE
Is Time in Range doesn’t support overnight range

### ISSUE THREAD

**Issue by zecanard** [sindresorhus/Actions#275]
### Description

The new `Is Time in Range` action available in build 84 doesn’t support overnight time ranges. Instead, it just seems to invert the start and end:
![Screenshot 2024-09-18 at 14 19 36](https://github.com/user-attachments/assets/c1ecfdc0-639a-46da-afbb-22f1e679f67e)
![Screenshot 2024-09-18 at 14 18 57](https://github.com/user-attachments/assets/bdeced0a-13fe-4495-a195-c51abcabfd6b)
![Screenshot 2024-09-18 at 18 10 03](https://github.com/user-attachments/assets/32309d4e-cc40-4812-9e2d-a240692ccfc9)

This is also true if the date is left blank (to test “now”).

Thanks in advance! Hopefully I can get rid of my shortcut soon 🙂

### macOS/iOS version

iOS 18.1b4

**Comment by sindresorhus** [comment]
Fixed in the latest TestFlight update (build 85).
