### ISSUE TITLE
Not showing in shortcuts (iOS)

### ISSUE THREAD

**Issue by d3faulter** [sindresorhus/Actions#278]
Nothing showing in shortcuts app on iOS 18 (iPhone 16). Restarted 3 times, no changes. 

---
Actions 3.4.0 (81) - com.sindresorhus.Actions
iOS 18.0
iPhone17,3

**Comment by sindresorhus** [comment]
Try to change the device language to something else and then back. Sometimes it also just takes some time for the actions to show up. This is not really related to the app as it's all controlled by iOS.
