### ISSUE TITLE
Action proposal: Git clone

### ISSUE THREAD

**Issue by Angelk90** [sindresorhus/Actions#28]
### Description

Hi @sindresorhus , i am trying to implement a git clone.

It seems to work, but I should make some changes.

Being that you are an expert, can I ask you a few things?

<img width="630" alt="Schermata 2022-03-20 alle 14 31 28" src="https://user-images.githubusercontent.com/20476002/159164760-b314c8a8-5fe8-45c2-a9af-0a85bee898a2.png">

<img width="367" alt="Schermata 2022-03-20 alle 14 32 08" src="https://user-images.githubusercontent.com/20476002/159164782-da1e99f0-cdd1-491d-a3c7-ec8363104c73.png">

**Comment by sindresorhus** [comment]
Support questions about the Shortcuts app are better asked here: https://www.reddit.com/r/shortcuts/
