### ISSUE TITLE
Action proposal: Magsafe-based Standby Mode Trigger

### ISSUE THREAD

**Issue by atomicaditya** [sindresorhus/Actions#280]
### Description

Would be nice to have Magsafe Standby mode as a trigger. In my routine, I see one case where it would be useful: When sleeping I put my phone on a magsafe dock in standby mode to charge. This could be a trigger to turn on the bedtime mode of my lights, and other home assistant based actions. I can also imagine usecases with home-office etc.

**Comment by sindresorhus** [comment]
This is unfortunately not possible. Actions cannot make triggers. I encourage you to send feedback to Apple about making something for this: https://feedbackassistant.apple.com
