### ISSUE TITLE
App UI extends too far vertically on small screens

### ISSUE THREAD

**Issue by FifiTheBulldog** [sindresorhus/Actions#3]
## Bug
On small screens, particularly the iPhone SE (1st generation), the slowly rocking app icon animation extends into the status bar, while the Send Feedback button is more than half cut off by the bottom edge of the screen.

## Desired fix
The vertical space used (especially between Open Shortcuts and Send Feedback, for example) should be adjusted depending on the screen size of the device so that everything fits comfortably.

## Screenshot
![IMG_8274](https://user-images.githubusercontent.com/63314105/142342850-909920a6-781d-47c9-9c77-fce2af8dc5fb.png)

### macOS/iOS version

iOS 15.2 public beta 3

**Comment by sindresorhus** [comment]
Fixed in v1.3.1
