### ISSUE TITLE
Action proposal: action to accept text (or document?) via drag and drop on macOS

### ISSUE THREAD

**Issue by mgrider** [sindresorhus/Actions#30]
### Description

Seems like it would be useful to be able to drop something onto a Shortcut in the dock. But is it even possible?

**Comment by sindresorhus** [comment]
It's possible natively since macOS 12.3. Just add a shortcut to the Dock and then you can drag and drop into it.

<img width="418" alt="Screen Shot 2022-03-30 at 23 57 53" src="https://user-images.githubusercontent.com/170270/160890382-66ebc71e-7308-457d-bc4b-2f566e9aa7e5.png">
