### ISSUE TITLE
Action proposal: Set Creation and Modification Date of Folder

### ISSUE THREAD

**Issue by FoxBlocks** [sindresorhus/Actions#31]
### Description

There's already one for files. Can one be made for folders, too?

**Comment by sindresorhus** [comment]
How would you use it?

The current action for files works on copies of the files that are used in the shortcut workflow. The original file is never modified, but rather a copy of it. However, for folders, it would only be possible to apply the change to the original input folder (in-place modification). Would that work for you?

**Comment by FoxBlocks** [comment]
I want to modify the timestamps of a folder that I copied from one iPad to another, because iOS doesn't do a good job of preserving folder timestamps when using Files' built-in compress feature.

I'm using the iOS version of Actions. It is impossible for an iOS app to modify folder timestamps?

**Comment by sindresorhus** [comment]
> It is impossible for an iOS app to modify folder timestamps?

There's no way to modify the original folder on iOS because of file system restrictions.

**Comment by sindresorhus** [comment]
I'll keep this issue open for a while in case anyone else has any good ideas about this.

**Comment by FoxBlocks** [comment]
> There's no way to modify the original folder on iOS because of file system restrictions.
That sucks. I wish Apple didn't make things difficult, but hey, it's Apple.

Thanks for your help. You're the only person on the Internet (as far as my own Google searching goes, anyway) who has given this piece of information. Seriously, you're super helpful, and I'm very grateful.

**Comment by sindresorhus** [comment]
Seems like this is now possible. You can try it out in the TestFlight build: https://github.com/sindresorhus/Actions/issues/63

You must enable the "Modify Original" setting.
