### ISSUE TITLE
Is Bluetooth on returns string instead of number/boolean

### ISSUE THREAD

**Issue by xplosionmind** [sindresorhus/Actions#32]
I do not know if it is only my problem, but in Shortcuts the `if` statements work only with numbers. Hence, I do not know how to create `if` conditions based on `Is Bluetooth On`. Currently, it returns `Yes` if it is on and `No` if it is not on. Could it return `1` and `0` or `true` and `false` respectively?

![image](https://user-images.githubusercontent.com/42862428/161003342-9cf955c1-9267-4283-8fb5-ce367ffa29f1.png)

**Comment by sindresorhus** [comment]
What you are seeing is just the label of the return value. The actual return value is a number.

**Comment by sindresorhus** [comment]
I'll remove the labels in the next update, but it should make no difference to the actual logic.
