### ISSUE TITLE
Is WiFi On

### ISSUE THREAD

**Issue by xplosionmind** [sindresorhus/Actions#33]
### Description

As there is the `Is Bluetooth On` feature, it would be very very useful to have `Is WiFi On` too.

**Comment by sindresorhus** [comment]
What would you use it for? There's already a "is online" action which is what most people actually want when they ask for an action like this ("WiFi on" doesn't always mean it has internet connection).

**Comment by xplosionmind** [comment]
Since in the dropdown menu of the iPhone the WiFi could never be switched off, but only "deactivated", I need a quick way to turn it completely on and off in one click.

**Comment by xplosionmind** [comment]
Thanks a lot anyways!

**Comment by moshed** [comment]
was this restriction ever lifted?

would be useful to check if wifi is on so I can run a corresponding shortcut that would let me know if wifi was turned on or off   

![image](https://github.com/user-attachments/assets/36ef8260-b812-46bd-8326-3a17931c92dd)
![image](https://github.com/user-attachments/assets/64ea356b-78e8-4fac-977e-8e8d27d175ed)
