### ISSUE TITLE
No output from "scan documents"

### ISSUE THREAD

**Issue by adamyonk** [sindresorhus/Actions#34]
### Description

![3B316912-3A4B-4831-9AEE-25AF0F7CD04E](https://user-images.githubusercontent.com/33258/161683091-d776dcc2-67c8-411c-a159-b3d3e2352da3.png)

I can't get anything to come out of this action. Is it supposed to be an image or PDF?

### macOS/iOS version

iOS 15.4

### Shortcut URL

https://www.icloud.com/shortcuts/24f9eecff97749e0b879122336f50fdc

**Comment by sindresorhus** [comment]
Per the action description, you need to add "wait and return" and "get clipboard" actions after this one.
