### ISSUE TITLE
Action proposal: Get Bluetooth Devices

### ISSUE THREAD

**Issue by jsiegenthaler** [sindresorhus/Actions#35]
### Description

Get audio playback destination works for Bluetooth audio devices, but sometimes I wish to see if another Bluetooth device is paired and connected.

Can you make an action that returns a list of Bluetooth paired devices, and the device status and type?

Status = Connected/Not Connected
Device Type = the device type as reported by the system (audio device, heartrate monitor, keyboard, etc)

Thanks!
Great App!

**Comment by sindresorhus** [comment]
Yeah. I will look into it. I just did a release yesterday, so it will be a while until I get to this.

**Comment by signe** [comment]
This is what I was hoping to find.  When I connect to power, I want to set my Focus based on whether a certain device is connected.  (e.g., if my motorcycle helmet is connected, I want it to turn on Driving when it connects to power)

I can do all of that except detect whether the device is connected or not...

**Comment by sindresorhus** [comment]
Done in v3: https://github.com/sindresorhus/Actions/releases/tag/v3.0.0

**Comment by sindresorhus** [comment]
> Device Type = the device type as reported by the system (audio device, heartrate monitor, keyboard, etc)

I was unable to find out how to get the device type, but I think the most common use-case is to just check for known devices.

**Comment by yur1xpp** [comment]
> Done in v3: https://github.com/sindresorhus/Actions/releases/tag/v3.0.0

@sindresorhus I noticed that it's unable to detect my car stereo, neither when it's connected nor disconnected. But in iOS bluetooth settings, it shows as connected as I was actually playing audio on it. I've tried increaded the timeout to 15s, and to show unnamed devices, but to no vail (these unnamed devices shows as disconnected in the returned list, so unlikely my car stereo). Do you have any idea?

**Comment by sindresorhus** [comment]
Don't comment on old issues. Open a new issue.
