### ISSUE TITLE
Action proposal: Get “specific” query from URL

### ISSUE THREAD

**Issue by seeker5084** [sindresorhus/Actions#36]
### Description

The built-in action "*Get Component of URL*" can get a query string from a URL, but it returns the **whole** query string. What I would like to use is an action that allows me to get a **specific** query value from a given URL.

i.e. URL: `https://www.youtube.com/watch/?v=aaaaaaaa&t=126`
Action: `Get query items named` `t` from `URL`
Output: `126`

Any chance?

**Comment by sindresorhus** [comment]
I'll add it in the next update.
