### ISSUE TITLE
Action Proposal: Humanize numbers

### ISSUE THREAD

**Issue by hexagonsun24** [sindresorhus/Actions#37]
It would be great to have a function that essentially does the same thing as the [humanize](https://github.com/jmoiron/humanize) package for Python. Ideally if there was a way to include all the functions, that'd be golden, but even just their integer humanization would be great.

For example, the action would take a number input such as "26548614862" and produce "26.5 billion" as output. A further refinement could be allowing a switch between "full" number and abbreviated numbers, so that the output could be "26.5B". 

In the python package referenced above, I believe it only applies to numbers 1,000,000 and over.

**Comment by sindresorhus** [comment]
> For example, the action would take a number input such as "26548614862" and produce "26.5 billion" as output

This is available in the latest update.
