### ISSUE TITLE
Action proposal: Calculations with SoulverCore

### ISSUE THREAD

**Issue by hexagonsun24** [sindresorhus/Actions#40]
### Description

An action that allows for natural language calculations, as found in Soulver 3 and Toolbox Pro (currently only on iOS and iPadOS). 

For example, the action would take text input like "$10 for lunch + 15% tip" and produce "$11.50" as the result.

The SoulverCore API is available [here](https://github.com/soulverteam/SoulverCore).

**Comment by sindresorhus** [comment]
It will be some months before I can get to this. Apple is changing the way to make shortcut actions in iOS 16, and I don't want to make more actions using the old way.

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/Actions/commit/308d198b2b4e02fbe60504301d3e29658d2b2f65

**Comment by sindresorhus** [comment]
Available in the TestFlight build: https://github.com/sindresorhus/Actions/issues/63

**Comment by hexagonsun24** [comment]
Did this make it into the official 2.0 release?

**Comment by hexagonsun24** [comment]
Love the implementation, is there any way to make a "compact" SI units for large numbers a toggle?

**Comment by sindresorhus** [comment]
I added a setting for this in 2.1.1
