### ISSUE TITLE
Action proposal: Get Focus 

### ISSUE THREAD

**Issue by shauder** [sindresorhus/Actions#41]
Would it be possible to get the state of Focus? It would also be great if the name of the focus could be returned if it is enabled. I am not sure if there is any better documentation but I found this: https://webcache.googleusercontent.com/search?q=cache:9JUDVOvViwwJ:https://developer.apple.com/forums/thread/682143+&cd=2&hl=en&ct=clnk&gl=us&client=firefox-b-1-d

**Comment by sindresorhus** [comment]
This will come in iOS 16.1 built-in: https://www.reddit.com/r/shortcuts/comments/xecqvk/ios_161_db1_new_get_current_focus_action/
