### ISSUE TITLE
iOS 15.0.1 compatibility

### ISSUE THREAD

**Issue by jontelang** [sindresorhus/Actions#46]
### Description

This is maybe more of a question, but I am on iOS 15.0.1 and built the app myself, surprisingly there were no issues. Is there a specific reason for being iOS 15.5 on the App Store version?

**Comment by sindresorhus** [comment]
Early iOS 15 versions had some SwiftUI bugs. I just target latest to avoid support with buggy iOS versions. I do t remember specifics.

**Comment by jontelang** [comment]
Fair enough. Curious what kind of SwiftUI issues there are seeing as the app is not a UI app (unless there is other UI exposed somewhere I haven't found).

**Comment by sindresorhus** [comment]
I don't remember specifics.
