### ISSUE TITLE
Action proposal: Set default printer

### ISSUE THREAD

**Issue by Pconde2A** [sindresorhus/Actions#48]
### Description

To replace ControlPlane that is no more supported, I would like to use Shortcuts.
One of the  feature that I use most is the ability to change the default Printer depending on the location (home, office, customer office sites, ...)
It would be great if you could add this action. 
Thx and take care

**Comment by sindresorhus** [comment]
I looked into this. There's no App Store compatible way to set the default printer. It is possible if an app is not sandboxed, but Actions is. I may make a separate app called Actions Plus or something in the future with actions that require more access, but not anytime soon. What is possible is to get the default printer and available printers. I will make actions for that later this year.

However, the solution for you is to use the "Run Shell Script" action with the following command:

```sh
lpoptions -d PRINTER_NAME
```

Example:

```sh
lpoptions -d HP_ENVY_5640_series
```

You can get a list of printer names by running in the Terminal:

```sh
lpstat -a
```

**Comment by sindresorhus** [comment]
Note to self: Get default printer with `NSPrintInfo.shared.printer`.

**Comment by sindresorhus** [comment]
Good news. I found a way to do it using some low-level APIs. It's included in the latest release.
