### ISSUE TITLE
Action proposal: Scan Documents to pdf

### ISSUE THREAD

**Issue by Pormplot** [sindresorhus/Actions#50]
The action „Scan Documents (iOS-only)“ currently copies the resulting images to the clipboard. When scanning several pages it sometimes takes a long time to retrieve these images. My suggestion is to automatically convert it to a .pdf and prompt for a location. Preferably with a configurable default location.

**Comment by sindresorhus** [comment]
Adding an option to merge the images into a single PDF is a good idea. However, saving the file is better handled by the built-in shortcut action.

**Comment by sindresorhus** [comment]
This is now available in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx And will be available in the next App Store update.
