### ISSUE TITLE
Action proposal: Set Display Rotation for any connected display

### ISSUE THREAD

**Issue by Cronbo** [sindresorhus/Actions#53]
### Description

Would be great to rotate my display with a keyboard shortcut. I have a 32" 4K which I use in landscape when sitting and portrait when standing, and automating the switch would be ideal. Thanks for all you do!

**Comment by sindresorhus** [comment]
Looks like it may be possible, but it requires using a private API, so it's likely Apple will reject it.

Note to self:
- https://stackoverflow.com/a/22477119/64949
- https://stackoverflow.com/a/17322010/64949
- https://github.com/jakehilborn/displayplacer/blob/036ecda1f7ebdb3a93d2dad09b6c82fb45aa0a54/displayplacer.c#L471
- https://developer.apple.com/documentation/coregraphics/1455299-cgdisplayrotation

**Comment by sindresorhus** [comment]
For now, you could download https://github.com/jakehilborn/displayplacer and call it using the "Run Shell Script" action.
