### ISSUE TITLE
Differing results for “is reachable” between Mac and iPhone

### ISSUE THREAD

**Issue by tamaracks** [sindresorhus/Actions#54]
Hi. Thanks for the great app! I’m getting different results running the “is reachable” action on my iPhone and my Mac.

The URL is for a local device on the network (a Hubitat home automation hub), but it has a full domain that gets resolved internally. So I’m feeding http://hubitat.haveno.net to the is reachable action (but alas you won’t be able to test).

The weird thing is that if I do this on my phone, it is always saying it’s unreachable. But when I tested it on my Mac, it does come back as reachable. 

I know it’s a hard one to troubleshoot and I don’t know for sure where the issue is. But I’m hoping maybe you have some insight that could point the way. I can reach the URL in a web browser fine on my phone. So it’s not unavailable in a general sense. How does Actions test for a connection?

---
Actions 1.13.1 (23) - com.sindresorhus.Actions
iOS 15.6.1
iPhone14,2

**Comment by tamaracks** [comment]
Meant to add, my Mac is an M1 MBP running the latest regular update from Apple.

**Comment by sindresorhus** [comment]
Does this shortcut succeed for you https://www.icloud.com/shortcuts/883b7a6dd54e48369dc343e37ef88a78 ?

**Comment by sindresorhus** [comment]
> How does Actions test for a connection?

It sends a HTTP HEAD request and validates whether it gets back a 2xx (200...299) status code.

The failure may be that your endpoint does not support HEAD requests or that it does not send back a success status code.

**Comment by sindresorhus** [comment]
The action now has more settings that will help get the wanted result.
