### ISSUE TITLE
Action proposal: adding replacement text

### ISSUE THREAD

**Issue by hchrzaniuk** [sindresorhus/Actions#55]
### Description

Hi, first of all your app is really useful. I was wondering if it’s possible to add direct shortcut to some Setting precisely to “text replacement” or even adding text replacement directly from some action. Thanks again !

**Comment by sindresorhus** [comment]
Opening the settings is unfortunately not possible. There are ways to do it, but Apple disallows apps doing it.

Here's how you can do it yourself: https://www.reddit.com/r/shortcuts/comments/tembsr/text_replacement_settings/

Adding to text replacements is not possible. It would require Apple to provide an official action for it.
