### ISSUE TITLE
Action proposal: toggle background sound / isBackgroundSoundOn/Off

### ISSUE THREAD

**Issue by peteruzek** [sindresorhus/Actions#56]
### Description

There is a new feature in Macos Ventura - Background sounds which i started using often, but it is burried deep in settings:

setting > accessibility > audio > background sound on/off

there is an API for shortcuts on iOS but not for MacOS

Thank you

![image](https://user-images.githubusercontent.com/1473495/189081604-a8fb6861-6ca9-43a2-a8cf-9f74fad379da.png)

**Comment by sindresorhus** [comment]
This is unfortunately not possible. There might be a way to change it with AppleScript, but Actions cannot run AppleScript. I'm sure someone will come up with a way to do this when macOS 13 is officially out.

I would recommend sending feedback to Apple that they should include a shortcut actions for it on macOS too.
