### ISSUE TITLE
Improvement: Checking local servers with 'Is reachable'

### ISSUE THREAD

**Issue by little-flag** [sindresorhus/Actions#58]
### Description

Not exactly a bug report, perhaps, but a request for an improvement.

I'd like to check whether a server on my local network is available before I try to connect via SSH. (Because Shortcuts has no error handling, there is no way of using if/then logic for this condition without an extra step.)

Currently, if I try, for example, `myMacbook.local` with 'Is reachable', the action returns 'No' if the remote machine is available, and times out if it is unavailable.

Perhaps this is out of scope for the current action, but it would be nice if it could be accommodated!

### macOS/iOS version

iPadOS 16.1 (20B5027f)

**Comment by sindresorhus** [comment]
Currently, the action assumes it's a web-server. I plan to add more settings for this soon.
