### ISSUE TITLE
Actions v2 testing

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Actions#63]
I have rewritten Actions from the ground up to use [App Intents](https://developer.apple.com/documentation/appintents). Actions should now be faster, but there may be bugs.

https://testflight.apple.com/join/fJGUrsZx

There are many new actions.

My goal is to publish the version officially when iOS 16.1 and macOS 13 is out.

**Comment by bradennapier** [comment]
This is all great. 

Currently I can't build from master due to Mac OS target not allowing for importing AppIntents.  Is that expected?  

I didn't look into it too much.  I'm running latest beta version of Mac OS 13.

**Comment by sindresorhus** [comment]
> Currently I can't build from master due to Mac OS target not allowing for importing AppIntents. Is that expected?

Yes. I plan to fix macOS support when the macOS 13 RC is out, in a couple of weeks.

**Comment by sindresorhus** [comment]
I'm happy to accept contributions, but I would prefer if you could open a new issue first where we can discuss exactly what actions to add, how they should work, etc.

**Comment by sindresorhus** [comment]
HomeKit is not available on macOS though. It would have to use Catalyst. Not sure how that would be possible here. Maybe some kind of embedded helper app.

**Comment by bradennapier** [comment]
It could be iOS only if possible but a catalyst app seems to make the most sense does it not?

Does catalyst remove the ability to use Mac OS apis in some way?  

Will open an issue

**Comment by sindresorhus** [comment]
> It could be iOS only if possible but a catalyst app seems to make the most sense does it not?

This app cannot be a Catalyst app as it requires access to APIs not available to Catalyst.

> Does catalyst remove the ability to use Mac OS apis in some way?

Yes, only a subset of macOS APIs are available to Catalyst apps.

**Comment by bradennapier** [comment]
Do you not have the latest 2.0 pushed to main ?  Looking to start from 2.0 / AppIntents while learning your structure but that doesn't seem to be ready even for iOS 16?  

I got it to run eventually but not seeing Actions in Shortcuts app

**Comment by bradennapier** [comment]
https://medium.com/geekculture/use-of-macos-specific-api-in-maccatalyst-apps-and-vice-versa-e7082a007b7c

**Comment by sindresorhus** [comment]
> https://medium.com/geekculture/use-of-macos-specific-api-in-maccatalyst-apps-and-vice-versa-e7082a007b7c

I'm aware of this technique, but it still requires your Mac app to be Catalyst which I'm not willing to do here.

**Comment by sindresorhus** [comment]
So if macOS support is important, it may be better to make a separate app for this.

**Comment by sindresorhus** [comment]
> Do you not have the latest 2.0 pushed to main ? Looking to start from 2.0 / AppIntents while learning your structure but that doesn't seem to be ready even for iOS 16?

The main branch is up to date and it's exactly what's in the latest TestFlight build.

Make sure you have the latest Xcode and try checking the build log for any problems building the App Intents.

**Comment by sindresorhus** [comment]
The TestFlight build is now also available for macOS 13.

**Comment by sindresorhus** [comment]
Version 2 is now officially out.
