### ISSUE TITLE
"Is Dark Mode On" always reports Yes

### ISSUE THREAD

**Issue by fregante** [sindresorhus/Actions#64]
### Description

https://user-images.githubusercontent.com/1402241/193439557-4e34790f-ca3f-4dfc-a043-160dea7c40b1.mov

### macOS/iOS version

12.6

**Comment by sindresorhus** [comment]
That's weird. However, I just tested on macOS 13 and it works fine for me there.

**Comment by Taxyovio** [comment]
I have been experiencing the exact opposite problem where it's always false.

**Comment by sindresorhus** [comment]
This should be fixed in the latest TestFlight update: https://testflight.apple.com/join/fJGUrsZx (Will be out on the App Store later this week)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/Actions/releases/tag/v2.1.0

**Comment by Taxyovio** [comment]
Unfortunate this didn't fixed it for me, running iPadOS 16.2.
