### ISSUE TITLE
Action proposal: Toggle Dark mode 

### ISSUE THREAD

**Issue by fregante** [sindresorhus/Actions#65]
### Description

Instead of building a condition with the Set Appearance action, it could be a single action to toggle the appearance.

<img width="637" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/193439577-2161f8df-42e5-424a-bd39-28201ae9a3d6.png">

Related:

- #64 
- I kinda want to see that standalone app because the Display dropdown requires two clicks 🤭

**Comment by sindresorhus** [comment]
This is not possible. Toggling dark mode requires certain access Apple will not grant to apps on the App Store. I know as I tried submitting a dark mode toggling app to the App Store last year.

**Comment by sindresorhus** [comment]
Also, this is already possible. Just click "Turn" and you can choose "Toggle" instead.

**Comment by fregante** [comment]
> Also, this is already possible. Just click "Turn" and you can choose "Toggle" instead.

Wow I'm a total Shortcuts noob 😅

**Comment by sindresorhus** [comment]
> Can apps not call Shortcuts?

Yes, but would have not been much of a convenience over specifying the if statements manually.

And they did not accept that method for my app as their argument was that the main functionality of an app cannot be dependent on a shortcut.
