### ISSUE TITLE
Action proposal: HomeKit Actions

### ISSUE THREAD

**Issue by bradennapier** [sindresorhus/Actions#66]
### Description

I am an engineer and honestly was going to add this myself for my own use… but it probably makes more sense to just make it public for everyone since it will be very useful. 

Currently the capabilities for HomeKit are sorely lacking. However, HomeKits potential is next level exciting.  I have installed and programmed many hundred thousand + dollar home automation systems from Crestron to Control4 to URC and HomeKit can accomplish much of what they can with some extra tools. 

1. It’s impossible to query rooms, zones, scenes, devices, etc to use in shortcuts 
2. No ability to control groups of values or query using parameters and execute actions on the resulting items
3. HomeBot does much of this but it is much out dated and can’t do much past lights and room queries

I would propose providing an updated method of doing this similar to HomeBot get items and set items. 

For example: 

Say I want a shortcut that can allow me to quickly set my home devices and such. 

![EB4D3859-08EA-4ACC-A96C-C9FDD6EEB3ED](https://user-images.githubusercontent.com/15365418/194694552-2504de1d-8f3d-4608-bd75-1a1c3ecccd1d.png)

it’s going to display a menu 

![59B45A4B-B126-4677-8E2B-BC067E2A2627](https://user-images.githubusercontent.com/15365418/194694588-dd4180eb-c3bf-419f-90ae-0227e74b1ee7.jpeg)

now when I select “televisions” - say I want a menu drop-down to do the following:

1. Allow me to select from menu to turn on or off any televisions in my home 
2. If the tv is currently on - menu item will says “____ Television Off” and selecting it will turn it off and opposite if tv was off. 

We would need to be able to query for all television types and each item would hold data such as current state, input, etc. 

I could then create menu items and use that information to populate the menus as needed. 

Additionally — the goal would be that we could then easily let user select from the menu which televisions were selected and with single item control those devices. 

—-

Other queries that should be possible:

1. Get all devices of given type that are in a given state 
2. Get all devices in a room 
3. Get all devices with a specific characteristic
4. Get zones / rooms  
5. Get rooms in zone 
6. Set all devices which match a filter and have a specific characteristic - set characteristic value or device state

—-

Most of these things should be possible in a couple actions, but I would imagine more could be considered.

**Comment by bradennapier** [comment]
It’s possible HomeKit could be such a broad api that it does warrant its own app with many different shortcut options. 

As for the Mac OS not having HomeKit that surprises me since there’s so many HomeKit apps for things like menu toolbar?

**Comment by jsiegenthaler** [comment]
I can control my TV using Home Automation natively. I do it daily. I have a scene called CNN that turns on my set top box, sets it to CNN and turns on TV and Home Theater. The TV settings can be read and controlled by Shortcuts. My Set-top Box controller offers all features and functions supported by HomeKit. Regards JochenSent from my iPhoneOn 8 Oct 2022, at 09:19, Braden Napier ***@***.***> wrote:﻿
It’s possible HomeKit could be such a broad api that it does warrant its own app with many different shortcut options.
As for the Mac OS not having HomeKit that surprises me since there’s so many HomeKit apps for things like menu toolbar?

**Comment by bradennapier** [comment]
? I am not sure what you are trying to say? 

Of course I can open home app and control tvs manually.  That's not the point at all. 

This is for writing more powerful shortcuts that are definitely not possible at the moment -- I mean you could manually list tvs and control them but this is about using logic to automate so adding a new tv for example would automatically be represented without changes.

**Comment by jsiegenthaler** [comment]
Ok. Sounded like you were saying you were unable to control tvs via shortcuts and automation. Which is not true, as you can. But it appears your goal is to do some auto discovery of devices in the home to allow menus to dynamically adjust. That’s also possible on some bridges: my Hue bridge provides that function. But not all bridges have this capability. Regards JochenSent from my iPhoneOn 8 Oct 2022, at 09:46, Braden Napier ***@***.***> wrote:﻿
? I am not sure what you are trying to say?
Of course I can open home app and control tvs manually.  That's not the point at all.
This is for writing more powerful shortcuts that are definitely not possible at the moment -- I mean you could manually list tvs and control them but this is about using logic to automate so adding a new tv for example would automatically be represented without changes.

**Comment by bradennapier** [comment]
No it's not possible with hue either I'm not sure you're understanding g at all what is trying to be done?

**Comment by jsiegenthaler** [comment]
Hue has APIs that enable you at any time to query the current hue config and get all rooms / zones / devices.As for what you want to do, you are correct, I am unsure of your goal. I just know some of the desired functionality exists in the native system. Regards JochenSent from my iPhoneOn 8 Oct 2022, at 10:36, Braden Napier ***@***.***> wrote:﻿
No it's not possible with hue either I'm not sure you're understanding g at all what is trying to be done?

**Comment by bradennapier** [comment]
Of course - but those apis are not available to shortcuts without a ton of custom work

**Comment by jsiegenthaler** [comment]
The APIs are available to shortcuts. That is a fact. Yes, you can make life easier if you want. I do and i did. But that doesn’t mean that their is _no_ API, and it doesn’t mean that the API is _not_ available. Sent from Mail for Windows From: Braden NapierSent: Saturday, 8 October 2022 14:12To: sindresorhus/ActionsCc: jsiegenthaler; CommentSubject: Re: [sindresorhus/Actions] Action proposal: HomeKit Actions (Issue #66) Of course - but those apis are not available to shortcuts without a ton of custom work—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by sindresorhus** [comment]
> It’s possible HomeKit could be such a broad api that it does warrant its own app with many different shortcut options.

Because of the limitation of not being able to support macOS HomeKit actions in this app, it's starting to sound like a separate app would be a better solution.

**Comment by bradennapier** [comment]
![image](https://user-images.githubusercontent.com/15365418/196690932-87be96de-fd72-40af-8316-0f143f2e3663.png)

![image](https://user-images.githubusercontent.com/15365418/196691142-2092632b-a7b4-467f-817d-eb7ab68582f0.png)

![image](https://user-images.githubusercontent.com/15365418/196691198-136f84bd-439d-4dd8-9982-4e4a7797e96e.png)

Coming along nicely!

**Comment by galdo320** [comment]
> ### Description
> I am an engineer and honestly was going to add this myself for my own use… but it probably makes more sense to just make it public for everyone since it will be very useful.
> 
> Currently the capabilities for HomeKit are sorely lacking. However, HomeKits potential is next level exciting. I have installed and programmed many hundred thousand + dollar home automation systems from Crestron to Control4 to URC and HomeKit can accomplish much of what they can with some extra tools.
> 
> 1. It’s impossible to query rooms, zones, scenes, devices, etc to use in shortcuts
> 2. No ability to control groups of values or query using parameters and execute actions on the resulting items
> 3. HomeBot does much of this but it is much out dated and can’t do much past lights and room queries
> 
> I would propose providing an updated method of doing this similar to HomeBot get items and set items.
> 
> For example:
> 
> Say I want a shortcut that can allow me to quickly set my home devices and such.
> 
> ![EB4D3859-08EA-4ACC-A96C-C9FDD6EEB3ED](https://user-images.githubusercontent.com/15365418/194694552-2504de1d-8f3d-4608-bd75-1a1c3ecccd1d.png)
> 
> it’s going to display a menu
> 
> ![59B45A4B-B126-4677-8E2B-BC067E2A2627](https://user-images.githubusercontent.com/15365418/194694588-dd4180eb-c3bf-419f-90ae-0227e74b1ee7.jpeg)
> 
> now when I select “televisions” - say I want a menu drop-down to do the following:
> 
> 1. Allow me to select from menu to turn on or off any televisions in my home
> 2. If the tv is currently on - menu item will says “____ Television Off” and selecting it will turn it off and opposite if tv was off.
> 
> We would need to be able to query for all television types and each item would hold data such as current state, input, etc.
> 
> I could then create menu items and use that information to populate the menus as needed.
> 
> Additionally — the goal would be that we could then easily let user select from the menu which televisions were selected and with single item control those devices.
> 
> —-
> 
> Other queries that should be possible:
> 
> 1. Get all devices of given type that are in a given state
> 2. Get all devices in a room
> 3. Get all devices with a specific characteristic
> 4. Get zones / rooms
> 5. Get rooms in zone
> 6. Set all devices which match a filter and have a specific characteristic - set characteristic value or device state
> 
> —-
> 
> Most of these things should be possible in a couple actions, but I would imagine more could be considered.

Do you know if there’s a way to verify is a device is not responding and to trigger another device?

**Comment by bradennapier** [comment]
Yes you can check accessory.isReachable and accessory.isBlocked to understand if an accessory is blocked and forward if needed.  

I'm not sure what your specific need would be but that would only happen within your own HomeKit app logic and not the home app itself.

If you wanted to implement a proxy-style handler that is automated and works with all HomeKit apps you would need homebridge or similar. 

As it happens my HomeKit version of actions will have a RPC implementation to my homebridge plugin that would allow things like that fairly easily-- but ofc relying on the homebridge in the middle is an extra moving part that needs to exist always. 

I personally run multiple homebridge servers... one for resource intensive instsnces using a micro pc I bought and one using raspberry pi for simple automation style implementations. 

This gives you complete freedom on unprecedented level... for example 

![image](https://user-images.githubusercontent.com/15365418/199735406-04cf4ec1-f3ce-4b03-820c-da0388d744bb.png)

Here i have a custom switch which I can program automations for when flipped ... if I set the timeout duration, when I turn it on it will begin a countdown seen in the UX that I can interrupt (reset to the timeout seconds again) with the "STOP" button, or even change the timeout as it's running and it will adjust dynamically 

If I set that timeout to 0 it will change to just being a normal switch.  

The possibilities are literally endless as this is actually implanting the HAP protocol same as a bridge like say Hue or Eve accessories would implement. 

In Homecuts app I am working on you can set all characteristics from shortcuts and control the states - so you can fully control this.
