### ISSUE TITLE
Action proposal: Get Active App(s) [iOS-iPadOS only]

### ISSUE THREAD

**Issue by FelipeRearden** [sindresorhus/Actions#70]
### Description

Hello @sindresorhus !!!

One of the things that I do a lot on iPadOs and iOS is navigating between apps while I am running a shortcut. 

I really miss a shortcut action that lets me **save** the App **NAME**  (or Apps if I am in Split View) that is active when I stsrt to run the shortcut. 

This way I can use the Action **Open App** to get back to the first/initial app in the end of the shortcut.

## My AP: Get Active App

It's a simple action that store the Name of the App that is active in the screen as a **text input**.

This action could be combined with the Action **Open App** which is able to receive text as an input 

ℹ️ This would be a great fit for the action **Choose from List Extended** because we need to get back to the Shortcuts app after selecting the item in the list.

## Example

📷 I created this simple Shortcut to demonstrate what this action could do in real world 

![C8FD02FA-00AF-48E2-8E53-EC4CDB9AFAE5](https://user-images.githubusercontent.com/85180696/195403976-37c13e58-b15e-4bf7-ac33-4ebd101b1fd6.jpeg)

📺 Running Shortcut

https://user-images.githubusercontent.com/85180696/195404766-880b4368-a563-4c82-af74-086b5c86bb08.MOV

---

I hope you like my suggestion !

Let me know if you need any information!

Have a great day!

**Comment by sindresorhus** [comment]
This is unfortunately not possible. On iOS, there's no way to get the name or any info about other running apps.

On macOS, you can use the `Get Running Apps` action.

**Comment by FelipeRearden** [comment]
> This is unfortunately not possible. On iOS, there's no way to get the name or any info about other running apps.

Hello @sindresorhus !!!!

Since the release of iOS/iPadOS 17 we now have new options to retrieve content from the active App that is running in the screen. 

This article from Macstories shows this feature from Goodlinks app and Things 3. 

> With version 1.8.5, GoodLinks joins [Cultured Code’s Things app](https://culturedcode.com/things/support/articles/9596775/) in offering a Shortcuts action that returns the current “state” of the app. Specifically, GoodLinks now comes with a ‘Get Current Link’ action that can be used to get the article that you’re currently reading inside the GoodLinks app. The item that will be returned in Shortcuts is a variable that contains properties for the article such as its title, URL, author, and more.

Source: https://www.macstories.net/reviews/goodlinks-adds-even-deeper-shortcuts-integration-with-ability-to-retrieve-current-article-selections-and-more/

<hr> 

Based on this I just wanna update this FR to check with you if this Fr would be feasible now based on this new features from iOS/iPadOS 17 🙏 🙏 🙏

Thanks for reading this ☀️

**Comment by FelipeRearden** [comment]
> An app can have an action that retrieves content from its own app, but an action cannot retrieve contents from a different app.

100% understood. I was afraid that was not possible :)

Thanks for the fast reply ☀️
