### ISSUE TITLE
Action proposal: Hide/Dismiss Share Sheet

### ISSUE THREAD

**Issue by FelipeRearden** [sindresorhus/Actions#71]
### Description

Hello @sindresorhus !!!

This AP is very simple to explain: many shortcuts that I have keeps the **Share Sheet** opened after its conclusion. 

It really bothers me that I have to manually dismiss the **Share Sheet** after running a shortcut from the Share Sheet.

### My AP: Hide Share Sheet

A simple action that hides the Share Sheet. It's the opposite behavior from the Action **Share**.

![2BF75E0A-B491-4BF9-961F-66C9CD6E39B3](https://user-images.githubusercontent.com/85180696/195406131-b407f85c-7356-4e69-abd3-552bb30aace5.jpeg)

Before I writing this AP, I checked and the **Share** action doesn't hide/dismiss the Share Sheet when it's open 😭

## Example

As you can see from the video, the Share Sheet keeps open after the shortcut is finished. 😡

https://user-images.githubusercontent.com/85180696/195407703-baa411fa-1284-4df1-b14b-590ae2b91129.MOV

---

Thanks for reading this !!!!

**Comment by sindresorhus** [comment]
This is unfortunately not possible. Third-party apps, like Actions, can in general not affect system UI or other apps on iOS.

The only thing I can think of is that you can use the "Go to Home Screen" action, but you may not want to leave the app.

I recommend you send feedback to Apple. The more feedback they get about this, the more likely they are to do something about it.

**Comment by FelipeRearden** [comment]
Thank you very much for the reply @sindresorhus !

> This is unfortunately not possible. Third-party apps, like Actions, can in general not affect system UI or other apps on iOS.
> The only thing I can think of is that you can use the "Go to Home Screen" action, but you may not want to leave the app.

100% understood . I really appreciate your reply  and suggestion :)

> I recommend you send feedback to Apple. The more feedback they get about this, the more likely they are to do something about it.

Roger that. I am gonna do this.

---

Thanks again ! I hope my other AP are feasible 🙏🙏🙏
