### ISSUE TITLE
"Scan QR codes in" does not detect QR code

### ISSUE THREAD

**Issue by workflowsguy** [sindresorhus/Actions#75]
### Description

For testing purposes, I ran this action with a PNG image (created from a PDF file) that contains a QR code encoding transferal data for an invoice. The action produces an empty output.

To verify, I used a Python script that wraps the [zxing-cpp library](https://github.com/zxing-cpp/zxing-cpp).
This correctly detects the QR code and outputs the encoded data

### macOS/iOS version

macOS 12.6

**Comment by sindresorhus** [comment]
Make sure you read the action description. You need to read the clipboard.

**Comment by workflowsguy** [comment]
I cannot verify this.

The action description I see is this:

```
Scans QR codes in the input image and returns their
message. By default, it only returns the message for the first
QR code. The messages are sorted by the physical size of
their QR code in ascending order (largest first).

Image
File

Result
Text
```

I tested both with the image containing the non-recognized barcode and another image containing two QR codes.

The two barcodes in the second image are recognized and returned as a list of text items as described in the action information.

For neither of the images the barcode texts are put on the clipboard.

**Comment by sindresorhus** [comment]
Sorry, I got the rules confused.

**Comment by sindresorhus** [comment]
If it's unable to detect the QR code, I'm not sure there's much I can do about it. The action simply uses the macOS API to detect QR codes. It's macOS doing the actual work.

If your able to send me (either here or at sindresorhus@gmail.com) a QR code that reproduces the issue, I'm happy to take a closer look.

**Comment by workflowsguy** [comment]
Thanks for the offer.
I did some futher experimenting and now was able to get the QR code recognized.

It seems like the image file has to have certain characteristics for a code to be successfully detected. I got a correct detection after converting the pdf to a 600 ppi png file. I will test this with several more files to see if this is actually the case.
