### ISSUE TITLE
Append to Note

### ISSUE THREAD

**Issue by unity** [sindresorhus/Actions#78]
### Description

Sharing a page / url to Notes using the native share sheet “Add to notes “ results in a nice thumbnails card in the note. 

Sharing from shortcuts with the built in “Append to notes” results in a text link

this action would allow to append a thumbnail card from a URL to a note
It would accept an existing note and a url as parameters

see screenshot for the current behaviours

![CD756884-2A9A-4934-8D6A-1B73ADA9CF40](https://user-images.githubusercontent.com/9458/199668643-4209be7f-18f3-424e-9c23-1996e102a8b3.png)

**Comment by sindresorhus** [comment]
This is unfortunately not possible. There is no way for a third-party app like Actions to interact with the Notes app.
