### ISSUE TITLE
Action proposal: Transcribe longer files

### ISSUE THREAD

**Issue by patrickrushton** [sindresorhus/Actions#79]
### Description

I'm finding that the Transcribe action only does about the first 30 words of an audio file. I'm not sure if that is expected behavior. It would be great to be able to Transcribe a full interview of up to one hour.

**Comment by sindresorhus** [comment]
The transcription functionality iOS provides is simply not very good (both API and result). Check out my Aiko app instead, which has higher quality transcription and unlimited duration: https://sindresorhus.com/aiko

**Comment by patrickrushton** [comment]
> The transcription functionality iOS provides is simply not very good (both API and result). Check out my Aiko app instead, which has higher quality transcription and unlimited duration: https://sindresorhus.com/aiko

Looks promising but unfortunately my Mac can' be upgraded to the required macOS 13.3
