### ISSUE TITLE
Action Proposal: Check if Ringer enabled

### ISSUE THREAD

**Issue by thechnet** [sindresorhus/Actions#8]
There is no way in the native Shortcuts app to detect if the iPhone's Ringer is enabled or disabled. This could be useful in some situations.

Just to be clear: I am only proposing a possibility to CHECK whether the Ringer is enabled.

**Comment by thechnet** [comment]
There is another third-party Shortcuts extension app (Toolbox Pro, https://apps.apple.com/ch/app/toolbox-pro-for-shortcuts/id1476205977?l=en), which supports such an action. The app locks it behind a paywall, but seeing as they offer it, it should technically be possible.

**Comment by sindresorhus** [comment]
This is available in the latest update.
