### ISSUE TITLE
IsOnline error

### ISSUE THREAD

**Issue by pbassham** [sindresorhus/Actions#81]
### Description

![899F20C4-FFFC-4A1B-B578-2763FC5A8044](https://user-images.githubusercontent.com/390996/201433253-8e59b3d1-143c-4980-b934-9ab874c2fec1.png)

This shortcut has been working until the latest update today. 

### macOS/iOS version

16.1.1

**Comment by sindresorhus** [comment]
Can you try restarting your device?

**Comment by pbassham** [comment]
Yep. Works now. Thanks!
