### ISSUE TITLE
Shortcuts couldn't convert from Text to NSString

### ISSUE THREAD

**Issue by envelen** [sindresorhus/Actions#83]
### Description

For List actions that contain Text
![IMG_0844](https://user-images.githubusercontent.com/110796556/203177999-f233d7ed-97ae-4211-9ee4-241cb269a743.jpeg)

### macOS/iOS version

Mac OS and iOS 2.1.1

**Comment by sindresorhus** [comment]
There are two Shortcuts (not Actions) bugs showing here. The first one is that it only returns a single item. That will be worked around in the next update. The second is that it shows an error message. This message is invalid and the result is correct. Just use "show result" action to see the actual value.

Note that there is already an actions to remove duplicate lines **from text** (not list).
