### ISSUE TITLE
Split Audio (or Video) File in Equal Parts

### ISSUE THREAD

**Issue by ricardonovelot** [sindresorhus/Actions#91]
### Description

Could be “Split my file in 30s intervals”

Or

“Split my file in 3 parts”

Haven’t seen this functionality anywhere, Also function as a workaround for the current Audio Transcriber that struggle with long files

**Comment by sindresorhus** [comment]
What's the use-cases for splitting videos?

**Comment by sindresorhus** [comment]
I'm going to pass on this. The use-case is unclear and there's a better transcription action available now: https://github.com/sindresorhus/Actions#want-more-shortcut-actions
