### ISSUE TITLE
How does one get the value from "Ask for Text with Timeout"?

### ISSUE THREAD

**Issue by dkermany** [sindresorhus/Actions#92]
### Description

The text value is not set as a magic variable and I am unable to reference it later in the shortcut. How do I reference the value of the returned text within the following if statement?
![signal-2022-12-23-045145_002](https://user-images.githubusercontent.com/6502959/209323589-5d033442-5481-4f15-bfc6-4c2d7e39a99d.jpeg)

### macOS/iOS version

16.2

**Comment by sindresorhus** [comment]
It's explained in the action description.

**Comment by dkermany** [comment]
I'm asking here because I cannot find it. Please say where I can find the action description at least

**Comment by sindresorhus** [comment]
Tap the small Actions app icon in the shortcut and select "show info".
