### ISSUE TITLE
Action proposal: Enable/Disable VPN

### ISSUE THREAD

**Issue by specter78** [sindresorhus/Actions#94]
### Description

The app is presently able to check vpn status. 

It should also be able to enable/disable vpn connection.

**Comment by sindresorhus** [comment]
I've had other requests for this, but it's unfortunately not possible. There's no way for a third-party app like Actions to toggle VPN.

It looks like the VPN provider could provide support for this, so I guess you could request it from your provider.

https://www.reddit.com/r/shortcuts/comments/jdke1l/can_anyone_please_tell_me_the_shortcut_for/
