### ISSUE TITLE
Action proposal: Global Variables

### ISSUE THREAD

**Issue by lublak** [sindresorhus/Actions#96]
### Description

Currently there are only variables under ShortCuts. But global variables could be very useful to store values.

**Comment by lublak** [comment]
@sindresorhus I now use Data Jar for this :) its an app which supports global values and you can use it with shortcut.
So it is not necessary if it is also supported here (of course it can be supported anyway).

**Comment by Niclaslach** [comment]
Hi,
You could have a look at the free app Data Jar, which offers permanent Key Value storage for shortcuts.

**Comment by lublak** [comment]
@Niclaslach i think its no needed anymore.
Apparently the function has been added :)
