### ISSUE TITLE
Action proposal: Notifications

### ISSUE THREAD

**Issue by lublak** [sindresorhus/Actions#97]
### Description

It can useful to get notifications from some events.
So if something get started by battery status show a notification: Battery is low < 30% we enabled the power switch for you!

So we need:
- Create (is built in)
- Edit
- Delete

**Comment by sindresorhus** [comment]
There already is a built-in action to create notifications.

**Comment by lublak** [comment]
@sindresorhus thanks i found it :) my os is in German but i searched in English because your app is in English.
But there is not edit or delete option there so i edit my issue.

**Comment by sindresorhus** [comment]
This is now available in the latest TestFlight build: https://testflight.apple.com/join/fJGUrsZx And will be available in the next App Store update.
